### ISSUE TITLE
Unable to run joinfaces - primefaces - bootsfaces - java11 inside a Docker container

### ISSUE THREAD

**Issue by brocoly27** [joinfaces/joinfaces#1214]
The source code is located here:

https://github.com/brocoly27/ca-zrm-ui

Basically, I'm able to display the initial page when I run the jar application on my local machine.

http://localhost:8080/health.jsf

However, when the same application is run inside a container, then I get the following exception:
I'm not sure what's happening, I've been dealing with this issue for days
Thanks
```
2021-09-01 23:24:58.365  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2021-09-01 23:24:58.428  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-09-01 23:24:58.448  INFO 1 --- [           main] com.ztarmobile.zrm.ZrmApplication        : Started ZrmApplication in 8.813 seconds (JVM running for 9.509)
2021-09-01 23:25:05.145  INFO 1 --- [nio-8080-exec-1] j.e.resource.webcontainer.jsf.context    : Exception when handling error trying to reset the response.

java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3050) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.connector.Request.getSession(Request.java:2494) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:908) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at com.sun.faces.context.ExternalContextImpl.getSession(ExternalContextImpl.java:155) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.context.ExternalContextWrapper.getSession(ExternalContextWrapper.java:456) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.view.ViewScopeManager.processPostConstructViewMap(ViewScopeManager.java:294) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.view.ViewScopeManager.processEvent(ViewScopeManager.java:263) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.view.ViewScopeEventListener.processEvent(ViewScopeEventListener.java:45) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:123) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:110) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:253) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:231) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:112) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:127) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.component.UIViewRoot.getViewMap(UIViewRoot.java:1680) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.component.UIViewRoot.getViewMap(UIViewRoot.java:1618) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at net.bootsfaces.listeners.AddResourcesListener.ensureExistBootsfacesComponent(AddResourcesListener.java:157) ~[bootsfaces-1.5.0.jar!/:1.5.0]
	at net.bootsfaces.listeners.AddResourcesListener.processEvent(AddResourcesListener.java:137) ~[bootsfaces-1.5.0.jar!/:1.5.0]
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:123) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:110) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:253) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:231) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:115) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:127) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:119) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:89) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.16.jar!/:2.3.16]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.4.jar!/:2.5.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2021-09-01 23:25:05.159 ERROR 1 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[FacesServlet]         : Servlet.service() for servlet [FacesServlet] in context with path [] threw exception [Cannot create a session after the response has been committed] with root cause
```

**Comment by larsgrefer** [comment]
The project in https://github.com/brocoly27/ca-zrm-ui contains xhtml-files in `src/main/webapp` but uses `jar` packaging.
This can not work correctly.

You either should use `war` packaging of some sort or move your webroot to `src/main/resources/META-INF/resources`

Also, when building a docker container from a spring boot application, just copying the repackaged application into a docker image isn't the best option. You should have a look at tools like [jib](https://github.com/GoogleContainerTools/jib) or [CNB](https://docs.spring.io/spring-boot/docs/2.5.x/maven-plugin/reference/htmlsingle/#build-image)

**Comment by brocoly27** [comment]
Thank you so much @larsgrefer I just fixed it, yeah, the problem was the location of the .xhtml file.
