### ISSUE TITLE
ClassNotFoundException: jakarta.validation.ConstraintViolation with mojarra-spring-boot-starter 5.0.0-m1

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#1383]
mojarra-spring-boot-starter 5.0.0-m1 usage raises ClassNotFoundException: jakarta.validation.ConstraintViolation with [jar](https://github.com/joinfaces/joinfaces-maven-jar-example) and [war](https://github.com/joinfaces/joinfaces-maven-war-example) packages.

The error happens with tomcat, jetty, and undertow.

It is specific to mojarra starter. It does not happen with myfaces-spring-boot-starter 5.0.0-m1.

In order to avoid it, I had to add jakarta.validation:jakarta.validation-api:3.0.0 dependency in [jar example](https://github.com/joinfaces/joinfaces-maven-jar-example/blob/1745ab21b8e184f0fffc2c739a03a081edc2d40e/pom.xml#L165) and [war example](https://github.com/joinfaces/joinfaces-maven-war-example/blob/e70d2f384d0c727971480d4c7f8d0aa3b2119be4/pom.xml#L165) package.

What do you think about pulling jakarta.validation:jakarta.validation-api dependency in mojarra-spring-boot-starter 5.0.x?

**Comment by larsgrefer** [comment]
This part here seems to be the "problem":

```
java.lang.NoClassDefFoundError: jakarta/validation/ConstraintViolation
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at com.sun.faces.util.Util.classHasAnnotations(Util.java:1255) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.application.ApplicationInstanceFactoryMetadataMap.onPut(ApplicationInstanceFactoryMetadataMap.java:54) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.application.ApplicationInstanceFactoryMetadataMap.onPut(ApplicationInstanceFactoryMetadataMap.java:27) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.util.MetadataWrapperMap.put(MetadataWrapperMap.java:78) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.processor.AbstractConfigProcessor.loadClass(AbstractConfigProcessor.java:285) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processHandlerClass(FaceletTaglibConfigProcessor.java:391) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processTags(FaceletTaglibConfigProcessor.java:341) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processTagLibrary(FaceletTaglibConfigProcessor.java:276) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.process(FaceletTaglibConfigProcessor.java:232) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:309) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:207) ~[jakarta.faces-3.0.2.jar:3.0.2]
```

While processing all defined tag libraries, Mojarra scans the related classes for annotations.
Scanning the class `org.omnifaces.taghandler.ValidateBean` results in an error if, jakarta.validation is not present.

So this problem only occurs if omnifaces is on the classpath, but jakarta.validation is not.

Im not sure if either omnifaces or mojarra (or their respective joinfaces starters) should pull jakarta.validation, or if this is indeed a bug in Mojarra itself.
MyFaces seems to be just fine with the class `org.omnifaces.taghandler.ValidateBean` not being loadable.

**Comment by larsgrefer** [comment]
I've opened https://github.com/eclipse-ee4j/mojarra/issues/5041 to see what the mojarra team thinks about this.

**Comment by dangnhdev** [comment]
[eclipse-ee4j/mojarra#5041](https://github.com/eclipse-ee4j/mojarra/issues/5041) <= This issue fixed, can we upgrade mojarra dependency version too?
