### ISSUE TITLE
Support Java 6

### ISSUE THREAD

**Issue by imgx64** [joinfaces/joinfaces#150]
Setting `java.version` to 1.6 in `joinfaces-example-war` project and then running it on Tomcat 7/Java 6 produces the following exception at runtime:

```
Caused by: java.lang.UnsupportedClassVersionError: org/joinfaces/annotations/JsfCdiToSpringApplicationContextInitializer : Unsupported major.minor version 51.0 (unable to load class org.joinfaces.annotations.JsfCdiToSpringApplicationContextInitializer)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2922)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1174)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1669)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:406)
	... 19 more
```

I tried it and it's possible to compile joinfaces with 1.6 with a few modifications (using explicit generic arguments instead of `<>`).

The only issue is tests, which seem to require Java 8 because of AssertJ 3.5. Will this cause a problem?

**Comment by persapiens** [comment]
hi @imgx64 ,

**java6 branch** pushed with initial support to java6. You should build it with java8 because of tests, but use the binaries with java6.

Could you try it?

Thanks in advance.

**Comment by persapiens** [comment]
@imgx64, `joinfaces-example-war` works `java 6 (oracle jre1.6.0_45)`, `tomcat 7.0.70` and ubuntu 16.04 using **java6 branch**.

You have to change the following property at pom.xml of `joinfaces-example-war` according to [Spring Boot Reference](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#_use_tomcat_7_with_maven):

```xml
<properties>
  <tomcat.version>7.0.70</tomcat.version>
</properties>
```

**Comment by imgx64** [comment]
I can confirm that `java6` branch is working with Java 6. Thanks for the `tomcat.version` tip.

**Comment by persapiens** [comment]
So let's merge `java6` to master right now!

Thank's for your helpful collaboration @imgx64 .

**Comment by persapiens** [comment]
@imgx64 **joinfaces 2.1.0** has just been released. It uses **spring boot 1.4.0** now.

Note that you should change **jackson.version** to use one version compatible with java 6 too.

```xml
<properties>
    <jackson.version>2.7.6</jackson.version>
</properties>
```
