### ISSUE TITLE
Startup error: Admin Faces and Weld CDI conflict - Ambiguous dependencies for type...

### ISSUE THREAD

**Issue by dangnhdev** [joinfaces/joinfaces#1628]
I've init a new project and can't get it to start with Springboot 3 + JoinFaces 5 with AdminFaces latest version
build.gradle file:
```groovy
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'org.springframework.boot' version '3.0.0'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'org.jetbrains.kotlin.jvm' version '1.7.21'
    id 'org.jetbrains.kotlin.plugin.spring' version '1.7.21'
    id 'org.joinfaces' version '5.0.0'
}

group = 'com.test'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    implementation {
        exclude module: "tomcat-spring-boot-starter"
        exclude module: "spring-boot-starter-tomcat"
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springBootAdminVersion', "3.0.0-M4")
}

dependencies {
    //spring core
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation ("org.springframework.boot:spring-boot-starter-web")
    implementation 'org.springframework.boot:spring-boot-starter-undertow'
    implementation 'de.codecentric:spring-boot-admin-starter-client'
    implementation 'de.codecentric:spring-boot-admin-starter-server'


    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    //joinfaces
    implementation ("org.joinfaces:jsf-spring-boot-starter")
    implementation "org.joinfaces:security-spring-boot-starter"
    implementation ("org.joinfaces:adminfaces-spring-boot-starter") 
   
   //kotlin
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'

    //utils
    implementation 'io.github.microutils:kotlin-logging-jvm:3.0.4'
}

dependencyManagement {
    imports {
        mavenBom "de.codecentric:spring-boot-admin-dependencies:${springBootAdminVersion}"
    }
}

tasks.withType(KotlinCompile) {
    kotlinOptions {
        freeCompilerArgs = ['-Xjsr305=strict']
        jvmTarget = '17'
    }
}

```
Startup Exception: 
```
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:164) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:578) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0.jar:3.0.0]
	at com.turtle.ecom.EcomAdminApplicationKt.main(EcomAdminApplication.kt:25) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-3.0.0.jar:3.0.0]
Caused by: java.lang.RuntimeException: org.jboss.weld.exceptions.DeploymentException: Exception List with 4 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type AdminConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.github.adminfaces.template.bean.BreadCrumbMB.adminConfig
  at com.github.adminfaces.template.bean.BreadCrumbMB.adminConfig(BreadCrumbMB.java:0)
  Possible dependencies: 
  - Managed Bean [class com.github.adminfaces.template.config.AdminConfig] with qualifiers [@Default @Any @Named],
  - Managed Bean [class org.joinfaces.autoconfigure.adminfaces.AdminConfigWrapper] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:285)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:162)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:515)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception 1 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type AdminConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.github.adminfaces.template.bean.LayoutMB.adminConfig
  at com.github.adminfaces.template.bean.LayoutMB.adminConfig(LayoutMB.java:0)
  Possible dependencies: 
  - Managed Bean [class com.github.adminfaces.template.config.AdminConfig] with qualifiers [@Default @Any @Named],
  - Managed Bean [class org.joinfaces.autoconfigure.adminfaces.AdminConfigWrapper] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:285)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:162)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:515)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception 2 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type AdminConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.github.adminfaces.template.bean.SkinMB.adminConfig
  at com.github.adminfaces.template.bean.SkinMB.adminConfig(SkinMB.java:0)
  Possible dependencies: 
  - Managed Bean [class com.github.adminfaces.template.config.AdminConfig] with qualifiers [@Default @Any @Named],
  - Managed Bean [class org.joinfaces.autoconfigure.adminfaces.AdminConfigWrapper] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:285)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:162)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:515)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception 3 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type AdminConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.github.adminfaces.template.security.LogoutMB.adminConfig
  at com.github.adminfaces.template.security.LogoutMB.adminConfig(LogoutMB.java:0)
  Possible dependencies: 
  - Managed Bean [class com.github.adminfaces.template.config.AdminConfig] with qualifiers [@Default @Any @Named],
  - Managed Bean [class org.joinfaces.autoconfigure.adminfaces.AdminConfigWrapper] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:285)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:162)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:515)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:257) ~[undertow-servlet-2.3.0.Final.jar:2.3.0.Final]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createManager(UndertowServletWebServerFactory.java:329) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:298) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-3.0.0.jar:3.0.0]
	... 13 common frames omitted
```

**Comment by larsgrefer** [comment]
Could you try again with JoinFaces 5.0.1?

**Comment by jomu78** [comment]
I confirm I have the same error when using 5.0.0. (maven based) After an update to 5.0.1 this error is gone and the application starts. 

But then I get a NPE when trying to access the page. It seems the AdminConfigWrapper which Specializes AdminConfig looses the injected AdminProperties.  The setter is called when the application is started but then when I access the page the injected properties are null which cause the NPE. 

Furthermore the injected properties have all Null-values even though they are (partly) defined in my application.yml. 

I will try to push the example application somewhere as reference.

**Comment by jomu78** [comment]
I pushed the example project to https://github.com/jomu78/tests as joinfaces-adminfaces-jdk17

**Comment by larsgrefer** [comment]
@jomu78 I was able to reproduce the NPE locally. Should be fixed with 5.0.2

**Comment by jomu78** [comment]
@larsgrefer : Works for me with JoinFaces 5.0.2
