### ISSUE TITLE
War deployment of Joinfaces 5.0.2 Startup Error.

### ISSUE THREAD

**Issue by seenukarthi** [joinfaces/joinfaces#1656]
[joinfaces-maven-war-example](https://github.com/joinfaces/joinfaces-maven-war-example) Dose not running in Tomcat 10.

I'm Getting the following error while starting Tomcat.

```log
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/ContextHandler$Context
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 48 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/ContextHandler$Context
	at org.joinfaces.ServletContextUtils.getClassLoader(ServletContextUtils.java:43)
	at org.joinfaces.autoconfigure.mojarra.JoinFacesAnnotationProvider.getAnnotatedClasses(JoinFacesAnnotationProvider.java:53)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:89)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 42 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.ContextHandler$Context
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1449)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1257)
	... 49 more
```

The error is @ [ServletContextUtils.java:43](https://github.com/joinfaces/joinfaces/blob/5.0.2/joinfaces/src/main/java/org/joinfaces/ServletContextUtils.java#L43), since Jetty classes are used but not packaged thus the error.

As per spring documentation on war deployment I have made the following changes.

```diff
diff --git a/pom.xml b/pom.xml
index 8d44e0c..e32049c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -183,6 +183,11 @@
             <artifactId>spring-boot-starter-test</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-tomcat</artifactId>
+            <scope>provided</scope>
+        </dependency>
         <dependency>
             <groupId>org.springframework.boot</groupId>
             <artifactId>spring-boot-starter-actuator</artifactId>
diff --git a/src/main/java/org/joinfaces/example/JoinFacesExampleApplication.java b/src/main/java/org/joinfaces/example/JoinFacesExampleApplication.java
index 264c375..88887e3 100644
--- a/src/main/java/org/joinfaces/example/JoinFacesExampleApplication.java
+++ b/src/main/java/org/joinfaces/example/JoinFacesExampleApplication.java
@@ -18,6 +18,7 @@ package org.joinfaces.example;

 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
+import org.springframework.boot.builder.SpringApplicationBuilder;
 import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

 /**
@@ -33,4 +34,9 @@ public class JoinFacesExampleApplication extends SpringBootServletInitializer {
        public static void main(String[] args) {
                SpringApplication.run(JoinFacesExampleApplication.class, args);
        }
+
+       @Override
+       protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
+               return application.sources(JoinFacesExampleApplication.class);
+       }
 }
~
```

The exception `java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/ContextHandler$Context` thrown from the catch block of the following code.

```java
@UtilityClass
public class ServletContextUtils {

	/**
	 * Jetty-safe variant of calling {@link ServletContext#getClassLoader()}
	 *
	 * @param servletContext The {@link ServletContext} on which {@link ServletContext#getClassLoader()} will be called.
	 * @return The {@link ClassLoader} of the given {@link ServletContext}.
	 */
	public ClassLoader getClassLoader(ServletContext servletContext) {
		try {
			return servletContext.getClassLoader();
		}
		catch (UnsupportedOperationException e) {
			if (servletContext instanceof ContextHandler.Context jettyContext) {
				boolean enabled = jettyContext.isEnabled();
				try {
					jettyContext.setEnabled(true);
					return servletContext.getClassLoader();
				}
				finally {
					jettyContext.setEnabled(enabled);
				}
			}
			else {
				throw e;
			}
		}
	}
}
```

So I debugged the application and found the actual exception on the `try` block the stack trace is below.

```log
java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getClassLoader(StandardContext.java:6747)
	at org.joinfaces.ServletContextUtils.getClassLoader(ServletContextUtils.java:40)
	at org.joinfaces.autoconfigure.mojarra.JoinFacesAnnotationProvider.getAnnotatedClasses(JoinFacesAnnotationProvider.java:53)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:89)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:179)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5180)
```

Complete Tomcat Log file [catalina.log](https://github.com/joinfaces/joinfaces/files/10662437/catalina.log)

**Comment by seenukarthi** [comment]
Complete Tomcat Log file [catalina.log](https://github.com/joinfaces/joinfaces/files/10662437/catalina.log)

**Comment by seenukarthi** [comment]
I found the cause. I was running Tomcat 10.0.x, but I should have used 10.1.x. in Tomcat 10.1.x it working without any error.
