### ISSUE TITLE
omnifaces not working in packaged jar in spring boot 3.2.0-RC1

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#1977]
Starting with spring boot 3.2.0-RC1, using joinfaces-maven-jar-example (jar package with tomcat), I got the following error with omnifaces-spring-boot-starter. 

```
2023-10-26T09:37:37.965-03:00  INFO 9088 --- [           main] o.j.example.JoinFacesExampleApplication  : Started JoinFacesExampleApplication in 8.761 seconds (process running for 16.75)
2023-10-26T09:37:42.978-03:00  WARN 9088 --- [nio-8080-exec-1] o.o.cdi.eager.EagerBeansWebListener      : Could not instantiate eager request scoped beans for request /login.faces. Possibly the CDI request scope is not active. If this is indeed the case, see JavaDoc on org.omnifaces.cdi.Eager on how to remedy this.

java.lang.NullPointerException: Cannot invoke "org.omnifaces.cdi.eager.EagerBeansRepository.instantiateByRequestURI(String)" because the return value of "org.omnifaces.cdi.eager.EagerBeansRepository.getInstance()" is null
        at org.omnifaces.cdi.eager.EagerBeansWebListener.requestInitialized(EagerBeansWebListener.java:70) ~[omnifaces-4.3.jar!/:4.3]
        at org.apache.catalina.core.StandardContext.fireRequestInitEvent(StandardContext.java:5584) ~[tomcat-embed-core-10.1.15.jar!/:na]
```

I got the similar error if I change tomcat by undertow.

If I change tomcat by jetty, I got other error:

```
2023-10-27T07:58:03.850-03:00  INFO 5212 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1346 ms
2023-10-27T07:58:04.141-03:00  INFO 5212 --- [           main] org.omnifaces.ApplicationInitializer     : Using OmniFaces version 4.3
2023-10-27T07:58:04.157-03:00  WARN 5212 --- [           main] o.e.jetty.ee10.webapp.WebAppContext      : Failed startup of context osbwej.JettyEmbeddedWebAppContext@736b21ee{application,/,b=[jar:file:///C:/programs/joinfaces-maven-jar-example/target/joinfaces-example-5.2.x.jar!/META-INF/resources/, file:/C:/Users/marcelo.fernandes.025/AppData/Local/Temp/jetty-docbase.8080.18020061004830182447/, URLResource@FC5841C6(jar:nested:///C:/programs/joinfaces-maven-jar-example/target/joinfaces-example-5.2.x.jar/!BOOT-INF/lib/jakarta.faces-4.0.4.jar!/META-INF/resources/), URLResource@5D70146C(jar:nested:///C:/programs/joinfaces-maven-jar-example/target/joinfaces-example-5.2.x.jar/!BOOT-INF/lib/primefaces-13.0.2-jakarta.jar!/META-INF/resources/), URLResource@8A40C8F5(jar:nested:///C:/programs/joinfaces-maven-jar-example/target/joinfaces-example-5.2.x.jar/!BOOT-INF/lib/primefaces-extensions-13.0.2-jakarta.jar!/META-INF/resources/), URLResource@A77D2A06(jar:nested:///C:/programs/joinfaces-maven-jar-example/target/joinfaces-example-5.2.x.jar/!BOOT-INF/lib/omnifaces-4.3.jar!/META-INF/resources/)],a=STOPPED,h=oeje10s.SessionHandler@49754e74{STOPPED}}

java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
        at org.omnifaces.ApplicationInitializer.onStartup(ApplicationInitializer.java:73) ~[omnifaces-4.3.jar!/:4.3]
        at org.joinfaces.servlet.ServletContainerInitializerRegistrationBean.lambda$customize$0(ServletContainerInitializerRegistrationBean.java:65) ~[joinfaces-unspecified.jar!/:unspecified]
        at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.callInitializers(ServletContextInitializerConfiguration.java:65) ~[spring-boot-3.2.0-RC1.jar!/:3.2.0-RC1]
        at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.configure(ServletContextInitializerConfiguration.java:54) ~[spring-boot-3.2.0-RC1.jar!/:3.2.0-RC1]
```

**Comment by larsgrefer** [comment]
WELD cannot handle the new jar:nested urls of spring boot:
```
2023-10-28T04:04:33.814+02:00  WARN 3284 --- [           main] org.jboss.weld.Bootstrap                 : WELD-ENV-000031: The bean archive reference jar:nested:/Users/larsgrefer/git/joinfaces/joinfaces/test-projects/tomcat-mojarra4/build/libs/tomcat-mojarra4-5.2.x-SNAPSHOT.jar/!BOOT-INF/lib/omnifaces-4.3.jar!/META-INF/beans.xml cannot be handled by any BeanArchiveHandler: [org.jboss.weld.environment.deployment.discovery.FileSystemBeanArchiveHandler@5f395ce1, org.jboss.weld.environment.servlet.deployment.ServletContextBeanArchiveHandler@19f02280]
```
