### ISSUE TITLE
Allow use of jsf-spring-boot-starter without declaring jsf-spring-boot-parent as parent

### ISSUE THREAD

**Issue by didiez** [joinfaces/joinfaces#208]
One may expect the use of the artifact `jsf-spring-boot-starter` the same way as other spring boot starters.

```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.2.RELEASE</version>
</parent>
<dependencies>
     <dependency>
         <groupId>org.joinfaces</groupId>
         <artifactId>jsf-spring-boot-starter</artifactId>
         <version>2.2.9</version>
      </dependency>
</dependencies>
```
Trying to start from command line (java -jar o spring boot executable jar) a simple proyect like the one below ends up crashing:

```
2016-11-16 15:20:29.727 ERROR 26357 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.config     : Unable to instantiate ExpressionFactory 'com.sun.el.ExpressionFactoryImpl'
2016-11-16 15:20:29.748 ERROR 26357 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.config     : Critical error during deployment: 

com.sun.faces.config.ConfigurationException: Parece que la versión JSP del contenedor es más antigua que la 2.1 y no se puede ubicar la fábrica de expresiones EL RI, com.sun.el.ExpressionFactoryImpl.  Si no utiliza JSP o EL RI, asegúrese de que el parámetro de inicialización de contexto, com.sun.faces.expressionFactory, esté definido correctamente.
	at com.sun.faces.config.ConfigureListener.registerELResolverAndListenerWithJsp(ConfigureListener.java:694)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:243)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4725)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-11-16 15:20:29.750 ERROR 26357 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class com.sun.faces.config.ConfigureListener

java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Parece que la versión JSP del contenedor es más antigua que la 2.1 y no se puede ubicar la fábrica de expresiones EL RI, com.sun.el.ExpressionFactoryImpl.  Si no utiliza JSP o EL RI, asegúrese de que el parámetro de inicialización de contexto, com.sun.faces.expressionFactory, esté definido correctamente.
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:292)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4725)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.faces.config.ConfigurationException: Parece que la versión JSP del contenedor es más antigua que la 2.1 y no se puede ubicar la fábrica de expresiones EL RI, com.sun.el.ExpressionFactoryImpl.  Si no utiliza JSP o EL RI, asegúrese de que el parámetro de inicialización de contexto, com.sun.faces.expressionFactory, esté definido correctamente.
	at com.sun.faces.config.ConfigureListener.registerELResolverAndListenerWithJsp(ConfigureListener.java:694)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:243)
	... 9 common frames omitted

2016-11-16 15:20:29.750 ERROR 26357 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : One or more listeners failed to start. Full details will be found in the appropriate container log file
2016-11-16 15:20:29.751 ERROR 26357 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors
2016-11-16 15:20:29.786  INFO 26357 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.lifecycle  : JSF1027: [null] los ELResolvers para JSF no se han registrado con el contenedor JSP.
2016-11-16 15:20:29.788 ERROR 26357 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.config     : Unexpected exception when attempting to tear down the Mojarra runtime

javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:101)
	at javax.el.FactoryFinder.find(FactoryFinder.java:197)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:197)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:168)
	at org.apache.jasper.runtime.JspApplicationContextImpl.<init>(JspApplicationContextImpl.java:46)
	at org.apache.jasper.runtime.JspApplicationContextImpl.getInstance(JspApplicationContextImpl.java:76)
	at org.apache.jasper.runtime.JspFactoryImpl.getJspApplicationContext(JspFactoryImpl.java:217)
	at com.sun.faces.el.ELUtils.getDefaultExpressionFactory(ELUtils.java:880)
	at com.sun.faces.el.ELUtils.getDefaultExpressionFactory(ELUtils.java:855)
	at com.sun.faces.config.ConfigureListener.contextDestroyed(ConfigureListener.java:345)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4772)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5411)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:74)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:87)
	... 19 common frames omitted
```

I think we should exclude the transitive dependency `javax.el-api` from `cdi-api` in jsf-spring-boot-starter.
I noticed that in the `<dependencyManagement>` of `jsf-spring-boot-parent` this dependency is explicitly excluded, but I'm inheriting another parent.

**Comment by persapiens** [comment]
You're totally right @didiez .

I'll use this opportunity to fix other dependency exclusions too.

**Comment by persapiens** [comment]
I've just pushed one implementation. Could you test it please?

**Comment by mtbadi39** [comment]
Hi @didiez, @persapiens, 
Just for info, in my spring-boot prjects, am using : 
` servletContext.setInitParameter("com.sun.faces.expressionFactory", "org.apache.el.ExpressionFactoryImpl");` 
from the **spring-boot-starter-tomcat** transitive dependency "tomcat-embed-el-8.0.33.jar"
... and its works.

**Comment by didiez** [comment]
Thanks for the tip @mtbadi39, but It doesn't feel right to me having the javax el-api in the classpath without the  implementation.
The starter artifact should be 'ready to use'. That's the philosophy behind spring boot starters
