### ISSUE TITLE
ExtensionsFilter stopped working in SpringApplication

### ISSUE THREAD

**Issue by gor4bag** [joinfaces/joinfaces#2628]
Hello, I am trying to use the Tomahawk library (customized for Jakarta) together with JoinFaces and MyFaces, but after migrating the configurations from web.xml to Java classes, the ExtensionsFilter stopped working.

SpringBoot 3.2.11
Joinfaces 5.2.5

`
@WebFilter(filterName = "MyfacesExtensionsFilter", urlPatterns = { "*.jsf", "/faces/myFacesExtensionResource/*" })
public class ExtensionsFilter implements Filter {
...
`

application.properties
```
joinfaces.faces.state-saving-method=client
joinfaces.myfaces.serialize-state-in-session=false
joinfaces.myfaces.number-of-views-in-session=20
joinfaces.myfaces.support-managed-beans=true
joinfaces.myfaces.support-jsp-and-faces-el=true
joinfaces.myfaces.error-handling=false

server.servlet.context-path=/sca
server.servlet.session.timeout=30m
spring.jpa.open-in-view=false
spring.http.multipart.enabled=false
```

Error:

```
[02/12/2024 18:29:52.907 -03] [---- traceId -----              ] [http-nio-8080-exec-2             ] [ERROR] [o.a.c.core.ContainerBase.[Tomcat].[localhost].[/sca].[FacesServlet]   ] Servlet.service() for servlet [FacesServlet] in context with path [/sca] threw exception [ExtensionsFilter not correctly configured. JSF mapping missing. JSF pages not covered. Please see: http://myfaces.apache.org/tomahawk/extensionsFilter.html] with root cause
java.lang.IllegalStateException: ExtensionsFilter not correctly configured. JSF mapping missing. JSF pages not covered. Please see: http://myfaces.apache.org/tomahawk/extensionsFilter.html
	at com.test.custom.myfaces.renderkit.html.util.AddResourceFactory.throwExtensionsFilterMissing(AddResourceFactory.java:375) ~[classes/:na]
	at com.test.custom.myfaces.renderkit.html.util.AddResourceFactory.checkEnvironment(AddResourceFactory.java:335) ~[classes/:na]
	at com.test.custom.myfaces.renderkit.html.util.AddResourceFactory.getInstance(AddResourceFactory.java:264) ~[classes/:na]
	at com.test.custom.myfaces.custom.navmenu.jscookmenu.HtmlJSCookMenuRenderer.addResourcesToHeader(HtmlJSCookMenuRenderer.java:382) ~[classes/:na]
	at com.test.custom.myfaces.custom.navmenu.jscookmenu.HtmlJSCookMenuRenderer.encodeBegin(HtmlJSCookMenuRenderer.java:341) ~[classes/:na]
	at jakarta.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:600) ~[myfaces-api-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:530) ~[myfaces-api-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554) ~[myfaces-api-3.0.2.jar:3.0.2]
	at org.apache.myfaces.shared.renderkit.html.HtmlGridRendererBase.renderChildren(HtmlGridRendererBase.java:376) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at org.apache.myfaces.shared.renderkit.html.HtmlGridRendererBase.encodeEnd(HtmlGridRendererBase.java:189) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:678) ~[myfaces-api-3.0.2.jar:3.0.2]
	at com.test.custom.myfaces.shared_tomahawk.renderkit.RendererUtils.renderChild(RendererUtils.java:441) ~[classes/:na]
	at com.test.custom.myfaces.shared_tomahawk.renderkit.RendererUtils.renderChildren(RendererUtils.java:425) ~[classes/:na]
	at com.test.custom.myfaces.shared_tomahawk.renderkit.RendererUtils.renderChild(RendererUtils.java:439) ~[classes/:na]
	at com.test.custom.myfaces.custom.layout.HtmlLayoutRenderer.renderTableCell(HtmlLayoutRenderer.java:159) ~[classes/:na]
	at com.test.custom.myfaces.custom.layout.HtmlLayoutRenderer.renderClassic(HtmlLayoutRenderer.java:63) ~[classes/:na]
	at com.test.custom.myfaces.custom.layout.HtmlLayoutRenderer.encodeEnd(HtmlLayoutRenderer.java:39) ~[classes/:na]
	at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:678) ~[myfaces-api-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:558) ~[myfaces-api-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554) ~[myfaces-api-3.0.2.jar:3.0.2]
	at org.apache.myfaces.shared.view.JspViewDeclarationLanguageBase.actuallyRenderView(JspViewDeclarationLanguageBase.java:351) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at org.apache.myfaces.shared.view.JspViewDeclarationLanguageBase.renderView(JspViewDeclarationLanguageBase.java:200) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73) ~[myfaces-api-3.0.2.jar:3.0.2]
	at com.test.mio4web.util.filter.csrf.CsrfViewHandler.renderView(CsrfViewHandler.java:44) ~[classes/:na]
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266) ~[myfaces-impl-3.0.2.jar:3.0.2]
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:206) ~[myfaces-api-3.0.2.jar:3.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117) ~[spring-security-web-6.2.7.jar:6.2.7]
	at com.test.sca.api.spring.intercept.SCAFilterSecurityInterceptor.invoke(SCAFilterSecurityInterceptor.java:55) ~[sca-spring-security-4.1.0.jar:4.1.0]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.util.filter.csrf.CSRFServletRedirectFilter.doFilter(CSRFServletRedirectFilter.java:49) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.util.filter.csrf.CSRFInputHiddenFilter.doFilter(CSRFInputHiddenFilter.java:49) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.util.filter.csrf.CrossSiteRequestForgeryFilter.doFilter(CrossSiteRequestForgeryFilter.java:53) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.util.filter.CookieFilter.doFilter(CookieFilter.java:41) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.util.filter.AuthenticateFilter.doFilter(AuthenticateFilter.java:37) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.ui.filter.JSFGetPostFilter.doFilter(JSFGetPostFilter.java:35) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at com.test.mio4web.ui.filter.AddSecurityHeadersFilter.doFilter(AddSecurityHeadersFilter.java:29) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.2.7.jar:6.2.7]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230) ~[spring-security-config-6.2.7.jar:6.2.7]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by larsgrefer** [comment]
Could you check with the "mapping" Actuator Endpoint, if your ExtensionsFilter is really applied?

**Comment by gor4bag** [comment]
> Could you check with the "mapping" Actuator Endpoint, if your ExtensionsFilter is really applied?

```
[10/12/2024 12:02:34.594 -03] [---- traceId -----              ] [main                             ] [DEBUG] [org.springframework.boot.web.servlet.ServletContextInitializerBeans   ] 

Mapping filters: 
webMvcObservationFilter urls=[/*] order=-2147483647, 
springSecurityFilterChain urls=[/*] order=-100, 
LogIntegrationFilter urls=[/SOAPSmplServlet] order=2147483647, 
AddSecurityHeadersFilter urls=[/*] order=2147483647, 
JSFGetPostFilter urls=[*.jsf] order=2147483647, 
SessionTimeoutFilter urls=[/secure/*] order=2147483647, 
AuthenticateFilter urls=[*.jsf] order=2147483647, 
CookieFilter urls=[*.jsf, /faces/*] order=2147483647, 
CrossSiteRequestForgeryFilter urls=[/*] order=2147483647, 
CSRFFInputHiddenFilter urls=[*.jsf, /servlet/*] order=2147483647, 
CSRFFServletRedirectFilter urls=[/*] order=2147483647, 
MyFacesExtensionResourceNotAllowFilter urls=[/faces/*] order=2147483647, characterEncodingFilter urls=[/*] order=-2147483648, requestContextFilter urls=[/*] order=-105, 
filterSecurityInterceptor urls=[/*] order=2147483647

[10/12/2024 12:02:34.595 -03] [---- traceId -----              ] [main                             ] [DEBUG] [org.springframework.boot.web.servlet.ServletContextInitializerBeans   ] 

Mapping servlets: 
FacesServlet urls=[/faces/*, *.jsf, *.faces, *.xhtml], dispatcherServlet urls=[/], 
DumpServlet urls=[/DumpServlet], 
OAPSpmlServlet urls=[/spml]
```

**Comment by larsgrefer** [comment]
Seems like the MyfacesExtensionsFilter is missing.

Instead of annotating the filter with "@WebFilter", you could try to declate a "FilterRegistrationBean" in your configuration in order to register the filter

**Comment by gor4bag** [comment]
```
@Configuration
public class FilterConfig {

    @Bean
    public FilterRegistrationBean<ExtensionsFilter> extensionsFilterRegistration() {
        FilterRegistrationBean<ExtensionsFilter> registrationBean = new FilterRegistrationBean<>();
        registrationBean.setFilter(new ExtensionsFilter());
        registrationBean.addUrlPatterns("*.jsf", "/faces/myFacesExtensionResource/*");
        registrationBean.setServletNames(List.of("Faces Servlet"));
        registrationBean.setOrder(1);
        return registrationBean;
    }
}
```

```
[10/12/2024 14:21:26.867 -03] [---- traceId -----              ] [main                             ] [DEBUG] [org.springframework.boot.web.servlet.ServletContextInitializerBeans   ] Mapping filters: webMvcObservationFilter urls=[/*] order=-2147483647, 

springSecurityFilterChain urls=[/*] order=-100, 
extensionsFilterRegistration servlets=[Faces Servlet] urls=[*.jsf, /faces/myFacesExtensionResource/*] order=1, 
LogIntegrationFilter urls=[/SOAPSmplServlet] order=2147483647, 
AddSecurityHeadersFilter urls=[/*] order=2147483647, 
JSFGetPostFilter urls=[*.jsf] order=2147483647, 
SessionTimeoutFilter urls=[/secure/*] order=2147483647, 
AuthenticateFilter urls=[*.jsf] order=2147483647, 
CookieFilter urls=[*.jsf, /faces/*] order=2147483647, 
CrossSiteRequestForgeryFilter urls=[/*] order=2147483647, 
CSRFFInputHiddenFilter urls=[*.jsf, /servlet/*] order=2147483647, 
CSRFFServletRedirectFilter urls=[/*] order=2147483647, 
MyFacesExtensionResourceNotAllowFilter urls=[/faces/*] order=2147483647, 
characterEncodingFilter urls=[/*] order=-2147483648, requestContextFilter urls=[/*] order=-105, 
filterSecurityInterceptor urls=[/*] order=2147483647
```

Now it registered, but why wasn't it registering directly?

**Comment by larsgrefer** [comment]
Maybe the ServletComponentScan wasn't active, was missing, or was looking at the wrong packages.

https://www.baeldung.com/spring-servletcomponentscan
https://docs.spring.io/spring-boot/api/java/org/springframework/boot/web/servlet/ServletComponentScan.html

**Comment by gor4bag** [comment]
It worked! It was only mapping the main package. Thank you very much!
