### ISSUE TITLE
ReflectionsException on startup

### ISSUE THREAD

**Issue by Primi2000** [joinfaces/joinfaces#264]
We start the joinfaces example with bootRun and get the exception below (using mac os).
Is there any dependency missing?

2017-03-09 13:56:54.907  WARN 14685 --- [  restartedMain] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

**org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/System/Library/Java/Extensions/libJ3DAudio.jnilib]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.**
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[reflections-0.9.10.jar:na]
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[reflections-0.9.10.jar:na]
        at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar:na]
        at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar:na]
        at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar:na]
        at org.joinfaces.JsfClassFactory.computeClasses(JsfClassFactory.java:185) [jsf-spring-boot-autoconfigure-2.3.6.jar:2.3.6]
        at org.joinfaces.JsfClassFactory.getAnnotatedClassMap(JsfClassFactory.java:157) [jsf-spring-boot-autoconfigure-2.3.6.jar:2.3.6]
        at org.joinfaces.JsfClassFactory.getAnnotatedClasses(JsfClassFactory.java:215) [jsf-spring-boot-autoconfigure-2.3.6.jar:2.3.6]
        at org.joinfaces.JsfClassFactory.getAllClasses(JsfClassFactory.java:204) [jsf-spring-boot-autoconfigure-2.3.6.jar:2.3.6]
        at org.joinfaces.mojarra.MojarraServletContextInitializer.onStartup(MojarraServletContextInitializer.java:76) [jsf-spring-boot-autoconfigure-2.3.6.jar:2.3.6]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:229) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory$Initializer.onStartup(UndertowEmbeddedServletContainerFactory.java:663) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:192) [undertow-servlet-1.4.11.Final.jar:1.4.11.Final]
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174) [undertow-servlet-1.4.11.Final.jar:1.4.11.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) [undertow-servlet-1.4.11.Final.jar:1.4.11.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.11.Final.jar:1.4.11.Final]
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239) [undertow-servlet-1.4.11.Final.jar:1.4.11.Final]
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:391) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:228) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.joinfaces.example.JoinFacesExampleApplicationMain.main(JoinFacesExampleApplicationMain.java:31) [main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.2.RELEASE.jar:1.5.2.RELEASE]

**Comment by larsgrefer** [comment]
see also https://github.com/joinfaces/joinfaces/issues/77#issuecomment-282548372

**Comment by mwelser** [comment]
Having the same issue - is not the same like #77 
i am using jar archive not war

**Comment by larsgrefer** [comment]
Maybe Springs `ClassPathScanningCandidateComponentProvider` can be used instead of the reflections library

**Comment by Primi2000** [comment]
We just ran some tests in a linux environment and there the problem does not occur.

**Comment by persapiens** [comment]
Hi @Primi2000 ,

Could you test your application with joinfaces-2.3.7-SNAPSHOT from branch master?

I look forward your answer.

**Comment by persapiens** [comment]
Hi @larsgrefer ,

Could you test your application against the problem related in #77 ?

I look forward your answer too.
