### ISSUE TITLE
Application not starting since Spring Boot 1.5+ upgrade

### ISSUE THREAD

**Issue by billbarni** [joinfaces/joinfaces#292]
I tried starting the application with many different combination, tried even abandoning Tomcat, but somehow it never finds the 'org.joinfaces.ServletContextConfigurer'.

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoClassDefFoundError: org/joinfaces/ServletContextConfigurer
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at br.com.tropicalia.Application.main(Application.java:10) [main/:na]
Caused by: java.lang.NoClassDefFoundError: org/joinfaces/ServletContextConfigurer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_101]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_101]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_101]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
	at org.joinfaces.primefaces.PrimefacesServletContextInitializer.onStartup(PrimefacesServletContextInitializer.java:38) ~[jsf-primefaces-spring-boot-autoconfigure-2.1.1.jar:2.1.1]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:229) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.jetty.ServletContextInitializerConfiguration$Initializer.callInitializers(ServletContextInitializerConfiguration.java:83) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.jetty.ServletContextInitializerConfiguration$Initializer.doStart(ServletContextInitializerConfiguration.java:72) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:844) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344) ~[jetty-servlet-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501) ~[jetty-webapp-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463) ~[jetty-webapp-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261) ~[jetty-servlet-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) ~[jetty-webapp-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.Server.start(Server.java:452) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.server.Server.doStart(Server.java:419) ~[jetty-server-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.4.v20170414.jar:9.4.4.v20170414]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.initialize(JettyEmbeddedServletContainer.java:93) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.<init>(JettyEmbeddedServletContainer.java:81) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getJettyEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:561) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:190) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	... 8 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.joinfaces.ServletContextConfigurer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
	... 51 common frames omitted
```

**Comment by jkolobok** [comment]
check your classpath.

**Comment by billbarni** [comment]
All required JARs are included. Im using Gradle.

```
compile group: "org.springframework.boot", name: "spring-boot-starter-web", version: "1.5.3.RELEASE"
    compile group: "org.springframework.boot", name: "spring-boot-starter-jetty", version: "1.5.3.RELEASE"
    compile group: "org.springframework.boot", name: "spring-boot-starter-jooq", version: "1.5.3.RELEASE"

    compile group: 'org.joinfaces', name: 'jsf-spring-boot-autoconfigure', version: '2.3.9'
    compile group: 'org.joinfaces', name: 'jsf-jetty-spring-boot-autoconfigure', version: '2.3.9'
    compile group: "org.joinfaces", name: "jsf-primefaces-spring-boot-autoconfigure", version: "2.1.1"
    compile group: "org.joinfaces", name: "jsf-omnifaces-spring-boot-autoconfigure", version: "2.1.1"
```

**Comment by billbarni** [comment]
The Gradle example found at:
https://github.com/joinfaces/jsf-test

is also not working.

**Comment by larsgrefer** [comment]
@billbarni It seems like you are mixing different versions of joinfaces (`2.3.9` and `2.1.1`).

For a working gradle example have a look at #260 (https://github.com/larsgrefer/joinfaces-gradle-example/)

**Comment by billbarni** [comment]
And how to add the Primefaces and Omnifaces dependencies? Just the pure jar's without the Joinfaces auxiliaries?

**Comment by billbarni** [comment]
I removed the wrong packages, now my autocomplete fields work only once.

**Comment by billbarni** [comment]
I'm closing the issue and rolling back to Spring 1.4. 
For some reason MANY issues appear in my project if I update it, probably not related to Joinfaces.

Thanks for the clarifications.
