### ISSUE TITLE
Application startup failed when project directory contains spaces

### ISSUE THREAD

**Issue by mtbadi39** [joinfaces/joinfaces#310]
Am not sure if its **joinfaces** related !
```
23:37:50 | ERROR | org.springframework.boot.SpringApplication                                       | Application startup failed
java.lang.IllegalArgumentException: Unable to create WebResourceSet from [D:\java\N%20Soumer\nsoumer-web\src\main\resources]
	at org.apache.catalina.webresources.StandardRoot.createWebResourceSet(StandardRoot.java:419)
	at org.joinfaces.tomcat.JsfTomcatApplicationListener.addClasspathResourceSets(JsfTomcatApplicationListener.java:176)
	at org.joinfaces.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:152)
	at org.joinfaces.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:38)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:101)
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at com.mtbadi39.nsoumer.web.EntryPoint.main(EntryPoint.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```
With project directory name is **N Soumer** with space in it, application startup failed
When i renamed it to **NSoumer**, application start successfully.

**My Config :** 
- JoinFaces 2.4.0 (with **spring-boot-starter-parent** as parent pom, **jsf-spring-boot-starter** as dependency)
- Netbeans 8.2
- Jdk1.8.0_102
- Windows 10

**Comment by persapiens** [comment]
hello @mtbadi39, could you try JoinFaces 3.0.0-SNAPSHOT and verify that #371 fixed this error?

Note that [JoinFaces 3.x has new starters](https://github.com/joinfaces/joinfaces/wiki/JoinFaces-Starters-3.x) and uses Spring Boot 2.x.

I look forward your answer.

**Comment by persapiens** [comment]
Thanks for your feedback @mtbadi39 

So, I'll close this issue.

If you think something is missing, please reopen it.
