### ISSUE TITLE
can't start application with 3.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by Philmasteryeah** [joinfaces/joinfaces#421]
Hey,
I cloned the current repo and cant start my application. I think it has something to do with the last changes in the jsf facesconfig classes by @larsgrefer 

```

2018-03-14 23:13:44.002  INFO 6096 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-14 23:13:44.026 ERROR 6096 --- [           main] javax.faces                              : Unable to obtain InjectionProvider from init time FacesContext. Does this container implement the Mojarra Injection SPI?
2018-03-14 23:13:44.026 ERROR 6096 --- [           main] javax.faces                              : Application was not properly initialized at startup, could not find Factory: javax.faces.context.FacesContextFactory. Attempting to find backup.
2018-03-14 23:13:44.030  WARN 6096 --- [           main] o.e.j.s.h.ContextHandler.application     : unavailable

java.lang.NullPointerException: null
	at javax.faces.CurrentThreadToServletContext.getFallbackFactory(CurrentThreadToServletContext.java:79) ~[javax.faces-2.3.3.jar:2.3.3]
	at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:537) ~[javax.faces-2.3.3.jar:2.3.3]
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:292) ~[javax.faces-2.3.3.jar:2.3.3]
	at javax.faces.webapp.FacesServlet.init(FacesServlet.java:374) ~[javax.faces-2.3.3.jar:2.3.3]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:665) [jetty-servlet-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:423) [jetty-servlet-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760) [jetty-servlet-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:207) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:141) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.philmaster.boot.JoinFacesApplication.main(JoinFacesApplication.java:10) [classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:496) [spring-boot-maven-plugin-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

2018-03-14 23:13:44.030  INFO 6096 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-03-14 23:13:44.030  INFO 6096 --- [           main] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-03-14 23:13:44.042  INFO 6096 --- [           main] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 12 ms
2018-03-14 23:13:44.062  INFO 6096 --- [           main] org.eclipse.jetty.server.session         : Stopped scavenging
2018-03-14 23:13:44.064  INFO 6096 --- [           main] o.e.j.s.h.ContextHandler.application     : Destroying Spring FrameworkServlet 'dispatcherServlet'
2018-03-14 23:13:44.066  INFO 6096 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@45e8190f{/,[file:///C:/Users/Philmaster/workspace/joinfaces-boot-jetty-cdi/target/classes/META-INF/resources/],UNAVAILABLE}
2018-03-14 23:13:44.070  INFO 6096 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-03-14 23:13:44.072 ERROR 6096 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:165) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.philmaster.boot.JoinFacesApplication.main(JoinFacesApplication.java:10) [classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:496) [spring-boot-maven-plugin-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: javax.servlet.ServletException: FacesServlet@450fcf==javax.faces.webapp.FacesServlet,jsp=null,order=-1,inst=false
```

**Comment by larsgrefer** [comment]
Is your project on github?

**Comment by Philmasteryeah** [comment]
yes, here https://github.com/Philmasteryeah/joinfaces-boot-jetty-cdi
change the jsf parent version to the current to reproduce the error

**Comment by larsgrefer** [comment]
I'm able to reproduce this.

Until we fixed this, you can set `jsf.faces-servlet.enabled=false` as workaround

**Comment by larsgrefer** [comment]
More Information: https://stackoverflow.com/a/20264804/3574494

**Comment by larsgrefer** [comment]
Since we register the `FacesServlet` ourselfs, the `com.sun.faces.config.ConfigureListener` is not registered by `com.sun.faces.config.FacesInitializer` anymore.

While Tomcat also finds the Listener inside mojarras `META-INF/jsf_core.tld` file, Jetty doesn't scan the TLD files

**Comment by Philmasteryeah** [comment]
thanks, It works with  `jsf.faces-servlet.enabled=false`

**Comment by larsgrefer** [comment]
This error happens, because JSF can't find its own `javax.faces.FactoryFinderInstance` it created earlier.

The `FactoryFinderInstance` is stored in `javax.faces.CurrentThreadToServletContext#applicationMap` using the ClassLoader as key. When first (and successfully) created the current ClassLoader is the `URLClassLoader` created by Joinfaces. When the FacesServlet is initialized and looks for the `FactoryFinderInstance` the ClassLoader is another one.
