### ISSUE TITLE
error read thema primefaces

### ISSUE THREAD

**Issue by av-git** [joinfaces/joinfaces#472]
org.reflections.ReflectionsException: could not get type for name org.primefaces.ultima.component.menu.UltimaMenu

```
org.reflections.ReflectionsException: could not get type for name org.primefaces.ultima.component.menu.UltimaMenu
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390) [reflections-0.9.11.jar:na]
	at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:409) [reflections-0.9.11.jar:na]
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:433) [reflections-0.9.11.jar:na]
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:418) [reflections-0.9.11.jar:na]
	at org.joinfaces.autoconfigure.servlet.initializer.JsfClassFactory.computeClasses(JsfClassFactory.java:184) [joinfaces-autoconfigure-3.2.0.jar:3.2.0]
	at org.joinfaces.autoconfigure.servlet.initializer.JsfClassFactory.getAnnotatedClassMap(JsfClassFactory.java:152) [joinfaces-autoconfigure-3.2.0.jar:3.2.0]
	at org.joinfaces.autoconfigure.servlet.initializer.JsfClassFactory.getAnnotatedClasses(JsfClassFactory.java:210) [joinfaces-autoconfigure-3.2.0.jar:3.2.0]
	at org.joinfaces.autoconfigure.servlet.initializer.JsfClassFactory.getAllClasses(JsfClassFactory.java:199) [joinfaces-autoconfigure-3.2.0.jar:3.2.0]
	at org.joinfaces.autoconfigure.mojarra.MojarraInitializerRegistrationBean.getClasses(MojarraInitializerRegistrationBean.java:50) [joinfaces-autoconfigure-3.2.0.jar:3.2.0]
	at org.joinfaces.autoconfigure.servlet.initializer.ServletContainerInitializerRegistrationBean.lambda$customize$0(ServletContainerInitializerRegistrationBean.java:58) [joinfaces-autoconfigure-3.2.0.jar:3.2.0]
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:54) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5204) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
Caused by: java.lang.NoClassDefFoundError: org/primefaces/component/api/Widget
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_162]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_162]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_162]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_162]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_162]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_162]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_162]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_162]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:148) ~[spring-boot-devtools-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_162]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_162]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadFromParent(TomcatEmbeddedWebappClassLoader.java:112) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.doLoadClass(TomcatEmbeddedWebappClassLoader.java:85) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:68) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388) [reflections-0.9.11.jar:na]
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.primefaces.component.api.Widget
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	... 39 common frames omitted
```

**Comment by persapiens** [comment]
hi @av-git ,

Could you provide a sample project to investigate better this issue?

I look forward your answer.

**Comment by av-git** [comment]
Olá Marcelo,
meu projeto utilizava a versão 2.4.1. Resolvi atualizar para versão 3.2.0.

-----------------------------------------
e deu o erro acima:
POM

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>br.com</groupId>
	<artifactId>av</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	
	
	<name>av</name>
	<description>Projeto av com JSF e Spring  boot</description>

	
	<parent>
		<groupId>org.joinfaces</groupId>	
		<artifactId>joinfaces-parent</artifactId>
		<version>3.2.0</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>

	
	<dependency>
		<groupId>org.joinfaces</groupId>
		<artifactId>jsf-spring-boot-starter</artifactId>
	</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.primefaces.themes</groupId>
			<artifactId>ultima-theme</artifactId>
			<version>1.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>
		
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>


-----------

Resolvi o problema add a dependência do primefaces 6.2 na mão 👍 
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>6.2</version>
</dependency>
------------
Mas na versão anterior não era necessário colocar explicitamente a dependencia do primefaces.

**Comment by persapiens** [comment]
hi @av-git,

I understand what you say because I'm Brazilian. However, community members usually understand and give more feedback if you speak English.

[JoinFaces 3.x starters](https://github.com/joinfaces/joinfaces/wiki/JoinFaces-Starters-3.x) semantically are different of [JoinFaces 2.x starters](https://github.com/joinfaces/joinfaces/wiki/JoinFaces-Starters-2.x).

You could use `primefaces-spring-boot-starter` instead of `jsf-spring-boot-starter` if you don't want to include primefaces dependency directly.

Cheers.

**Comment by av-git** [comment]
Perfect. thank you

**Comment by persapiens** [comment]
You are welcome @av-git .

So, could you close the issue?
