### ISSUE TITLE
Could not find backup for factory javax.faces.context.FacesContextFactory

### ISSUE THREAD

**Issue by djeverson** [joinfaces/joinfaces#487]
Hello,  

We are shifting a JEE app from Wildfly to Spring Boot.   

I've updated our pom.xml to use joinfaces:

```
<parent>
	<groupId>org.joinfaces</groupId>
	<artifactId>joinfaces-parent</artifactId>
	<version>3.2.0</version>
	<relativePath />  
</parent>

<dependency>
	<groupId>org.joinfaces</groupId>
	<artifactId>primefaces-spring-boot-starter</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-aop</artifactId>
	<version>2.0.2.RELEASE</version>
</dependency>
<dependency>
	<groupId>org.springframework.data</groupId>
	<artifactId>spring-data-jpa</artifactId>
	<version>2.0.6.RELEASE</version>
</dependency>
```

Running the Spring Boot application from Eclipse Oxygen reports the application has started.  However, when I navigate to a page in the application in the browser, I get the following stacktrace:

```
2018-05-13 21:29:24.539  INFO 95060 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-05-13 21:29:24.591  INFO 95060 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-05-13 21:29:24.594  INFO 95060 --- [           main] com.viableit.AthApplication                  : Started AthApplication in 11.857 seconds (JVM running for 12.267)
2018-05-13 21:29:33.535 ERROR 95060 --- [nio-8080-exec-1] javax.faces                              : Unable to obtain InjectionProvider from init time FacesContext. Does this container implement the Mojarra Injection SPI?
2018-05-13 21:29:33.535 ERROR 95060 --- [nio-8080-exec-1] javax.faces                              : Application was not properly initialized at startup, could not find Factory: javax.faces.context.FacesContextFactory. Attempting to find backup.
2018-05-13 21:29:33.539 ERROR 95060 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : StandardWrapper.Throwable

java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.FacesContextFactory.
  at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:541) ~[javax.faces-2.3.4.jar:2.3.4]
  at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:292) ~[javax.faces-2.3.4.jar:2.3.4]
  at javax.faces.webapp.FacesServlet.init(FacesServlet.java:374) ~[javax.faces-2.3.4.jar:2.3.4]
  at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

2018-05-13 21:29:33.541 ERROR 95060 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[FacesServlet]         : Allocate exception for servlet [FacesServlet]

java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.FacesContextFactory.
  at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:541) ~[javax.faces-2.3.4.jar:2.3.4]
  at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:292) ~[javax.faces-2.3.4.jar:2.3.4]
  at javax.faces.webapp.FacesServlet.init(FacesServlet.java:374) ~[javax.faces-2.3.4.jar:2.3.4]
  at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar:8.5.29]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

I see that the Mojarra jars were resolved in the pom.xml so they are present.  I don't see any MyFaces jar files.  I am not sure how to proceed further in troubleshooting this issue.  Does anybody have any ideas that could help me out?  

Thanks!
Dave

**Comment by larsgrefer** [comment]
Please run the app with `--debug` or `debug=true` an post the full startup log.

**Comment by djeverson** [comment]
Hi Lars, 

Please see the attached.  

[log.txt](https://github.com/joinfaces/joinfaces/files/2002958/log.txt)

**Comment by mtbadi39** [comment]
[This](https://stackoverflow.com/questions/18897900/java-lang-illegalstateexceptioncould-not-find-backup-for-factory-javax-faces-ap#18898156) my help !

**Comment by larsgrefer** [comment]
@djeverson Seems like `com.sun.faces.config.ConfigureListener#contextInitialized` isn't called.

Please try to add this to your `@SpringBootApplication`:

```java
@Bean
public com.sun.faces.config.ConfigureListener mojarraConfigureListener() {
    return new com.sun.faces.config.ConfigureListener()
}
```

In addition do that, it would be great if you could provide a [MCVE](https://stackoverflow.com/help/mcve) project (or even access to the real project), so we can investigate why the listener isn't called.

**Comment by larsgrefer** [comment]
@djeverson Is your problem resolved?

**Comment by lucksjb** [comment]
I´m following  this post, and this code 
@Bean
public com.sun.faces.config.ConfigureListener mojarraConfigureListener() {
    return new com.sun.faces.config.ConfigureListener()
} 
solve the "Could not find backup for factory javax.faces.context.FacesContextFactory".

now, I have problem to inject a service into a converter

**Comment by larsgrefer** [comment]
@lucksjb Please open a new issue for your problem

**Comment by vitsin** [comment]
I am using joinfaces v4.1.0-rc1 and issue of loading FacesServlet on start up still in place: Could not find backup for factory javax.faces.lifecycle.LifecycleFactory.
joinfaces.faces-servlet.load-on-startup=1
The workaround still must be applied, unfortunately:
`@Bean
public com.sun.faces.config.ConfigureListener mojarraConfigureListener() {
    return new com.sun.faces.config.ConfigureListener()
}`

Any plans to add fix permanently ?
regards

**Comment by larsgrefer** [comment]
@vitsin Can you provide an example project where I can investigate why the listener isn't called?

**Comment by vitsin** [comment]
@larsgrefer pls see repository for my current example project: joinfaces_jsf_rewrite_example.
Would love to hear any feedback from you and all others. Thanks.

**Comment by larsgrefer** [comment]
@vitsin In your case the following line causes the problem:

```properties
server.tomcat.additional-tld-skip-patterns=*.jar
```

tomcat would normally find the ConfigureListener in `jakarta.faces-2.3.13.jar!/META-INF/jsf_core.tld:64`

**Comment by vitsin** [comment]
@larsgrefer, once I've removed `server.tomcat.additional-tld-skip-patterns` from application.properties, the following error started to pop up during spring-boot start:


```
29-Nov-2019 15:35:51 INFO  [restartedMain] [o.a.c.c.StandardService] - Starting service [Tomcat]
29-Nov-2019 15:35:51 INFO  [restartedMain] [o.a.c.c.StandardEngine] - Starting Servlet engine: [Apache Tomcat/9.0.27]
29-Nov-2019 15:35:51 WARN  [restartedMain] [o.a.t.u.s.StandardJarScanner] - Failed to scan [file:/bla/.m2/repository/xalan/xalan/2.7.2/xercesImpl.jar] from classloader hierarchy
java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:236)
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65)
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:374)

```

The jar file xercesImpl.jar does not exist in OS, but instead of it there is a xalan-2.7.2.jar.
I do not set up in any place xalan in pom.xml, its probably downloaded/used by Tomcat itself.

**Comment by jacob2221** [comment]
@vitsin Were you able to resolve the latest error?
