### ISSUE TITLE
Tomcat won't start after upgrade to joinfaces 3.2.3 (missing CDI API)

### ISSUE THREAD

**Issue by stochmalm** [joinfaces/joinfaces#508]
After upgrade to joinfaces 3.2.3 I changed CDI annotations to spring ones and now when I run app from maven (spring-boot:run) tomcat won't start because of missing CDI context:

```
java.lang.NoClassDefFoundError: javax/enterprise/context/spi/Contextual
 at java.lang.Class.forName0(Native Method) ~[?:1.8.0_152]
 at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_152]
 at com.sun.faces.util.Util.loadClass(Util.java:333) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.processor.ApplicationConfigProcessor.addSystemEventListener(ApplicationConfigProcessor.java:1032) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.processor.ApplicationConfigProcessor.process(ApplicationConfigProcessor.java:370) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:155) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:138) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:155) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:246) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:443) ~[javax.faces-2.3.5.jar:2.3.5]
 at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:237) [javax.faces-2.3.5.jar:2.3.5]
 at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790) [tomcat-embed-core-8.5.31.jar:8.5.31]
 at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256) [tomcat-embed-core-8.5.31.jar:8.5.31]
 at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
 at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.31.jar:8.5.31]
 at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.31.jar:8.5.31]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.ClassNotFoundException: javax.enterprise.context.spi.Contextual
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
 ... 20 more
```

Do I really need to provide CDI dependency? As for now I added it in runtime scope in order to make tomcat start.

joinfaces-parent 3.2.3,
Spring Boot v2.0.3.RELEASE, Spring v5.0.7.RELEASE,
Mojarra.

**Comment by persapiens** [comment]
Hi @stochmalm ,

Could you take a look at #505 and #503 ?

I look forward your answer.

**Comment by larsgrefer** [comment]
Seems like something on you classpath is compiled agains some CDI classes. Unfortunately most projects which use CDI are declaring their `cdi-api`-dependency as `provided`, so it won't be pulled in your project.

Manually adding the cdi-api to your (runtime-)classpath is a valid workaround.
