### ISSUE TITLE
java.lang.ClassCastException: com.sun.faces.facelets.compiler.UIInstructions cannot be cast to org.primefaces.model.menu.MenuElement

### ISSUE THREAD

**Issue by bjorntj** [joinfaces/joinfaces#615]
After upgrading to Joinfaces 4.0.0 from 3.3.0-rc5, I get the following exception:

`Caused by: java.lang.ClassCastException: com.sun.faces.facelets.compiler.UIInstructions cannot be cast to org.primefaces.model.menu.MenuElement
	at org.primefaces.california.component.menu.CaliforniaMenuRenderer.encodeElements(CaliforniaMenuRenderer.java:53)
	at org.primefaces.california.component.menu.CaliforniaMenuRenderer.encodeMarkup(CaliforniaMenuRenderer.java:43)
	at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:117)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:949)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1912)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:918)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:491)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
`

Not sure which change has caused this..?

**Comment by persapiens** [comment]
Could you take a look [here](https://stackoverflow.com/questions/20188092/java-lang-classcastexception-com-sun-faces-facelets-compiler-uiinstructions-can)?

**Comment by bjorntj** [comment]
Well, that pointed me in the right direction.. I have some jsf configurations in my application property file, that no longer seems to work. 
And I see I was a little quick in reading the change log, see i need to prefix my settings using joinfaces now... And now it works, thx... :)

**Comment by persapiens** [comment]
Please see [Migration Guide](https://github.com/joinfaces/joinfaces/wiki/JoinFaces-4-Migration-Guide) about breaking changes.

**Comment by bjorntj** [comment]
Will do.. 👍

**Comment by larsgrefer** [comment]
@bjorntj Can we close this ticket or do you still have problems?
