### ISSUE TITLE
DevTools: Ability to reload XHTML page on the fly.

### ISSUE THREAD

**Issue by melloware** [joinfaces/joinfaces#621]
**JoinFaces:** 3.3.0-rc5
**Spring Boot:** 2.1.1
**Using:** Undertow, MyFaces, PrimeFaces, OmniFaces 3.2

I am trying to achieve being able to edit code while the app is running in DEV mode.  I want to be able to edit XHTML pages and have them show up **without** having to restart the app. Is this possible?

I am using Spring Boot DevTools which provides for hot reloading of the app when you make changes to the code.
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
        </dependency>
```

However any time a change is made when the app reloads it gets the following error.

```
2018-12-18 17:49:44.280  INFO 448 --- [       Thread-8] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.1.RELEASE)

2018-12-18 17:49:44.387  INFO 448 --- [  restartedMain] o.i.i.InventoryManagerApplication        : Starting InventoryManagerApplication on LAPTOP-TJEAGHK8 with PID 448 (C:\dev\ti\inventory-manager\target\classes started by elefkof in C:\dev\ti\inventory-manager)
2018-12-18 17:49:44.387  INFO 448 --- [  restartedMain] o.i.i.InventoryManagerApplication        : No active profile set, falling back to default profiles: default
2018-12-18 17:49:44.740  INFO 448 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.joinfaces.autoconfigure.javaxfaces.JsfBeansAutoConfiguration$Jsf2_3AutoConfiguration' of type [org.joinfaces.autoconfigure.javaxfaces.JsfBeansAutoConfiguration$Jsf2_3AutoConfiguration$$EnhancerBySpringCGLIB$$e788518e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-18 17:49:44.747  INFO 448 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.joinfaces.autoconfigure.javaxfaces.JsfBeansAutoConfiguration' of type [org.joinfaces.autoconfigure.javaxfaces.JsfBeansAutoConfiguration$$EnhancerBySpringCGLIB$$9bb6d694] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-18 17:49:44.794  INFO 448 --- [  restartedMain] o.j.a.u.UndertowAutoConfiguration        : Setting Undertow classLoader to META-INF/resources directory
2018-12-18 17:49:44.820  WARN 448 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2018-12-18 17:49:44.821  INFO 448 --- [  restartedMain] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2018-12-18 17:49:44.821  INFO 448 --- [  restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 434 ms
2018-12-18 17:49:44.929  INFO 448 --- [  restartedMain] org.omnifaces.ApplicationInitializer     : Using OmniFaces version 3.2
2018-12-18 17:49:45.487  INFO 448 --- [  restartedMain] vletContainerInitializerRegistrationBean : Resolving classes for org.apache.myfaces.ee.MyFacesContainerInitializer took 0.549s
2018-12-18 17:49:45.487  INFO 448 --- [  restartedMain] o.a.m.ee.MyFacesContainerInitializer     : Using org.apache.myfaces.ee.MyFacesContainerInitializer
2018-12-18 17:49:45.490  INFO 448 --- [  restartedMain] o.j.weld.environment.servletWeldServlet  : WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
2018-12-18 17:49:45.507  INFO 448 --- [  restartedMain] org.jboss.weld.Bootstrap                 : WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2018-12-18 17:49:45.511  INFO 448 --- [  restartedMain] org.jboss.weld.Event                     : WELD-000411: Observer method [BackedAnnotatedMethod] org.apache.myfaces.cdi.JsfArtifactProducerExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2018-12-18 17:49:45.516  INFO 448 --- [  restartedMain] org.jboss.weld.Event                     : WELD-000411: Observer method [BackedAnnotatedMethod] org.apache.myfaces.config.annotation.CdiAnnotationProviderExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2018-12-18 17:49:45.527  INFO 448 --- [  restartedMain] o.j.weld.environment.servletUndertow     : WELD-ENV-001302: Undertow detected, CDI injection will be available in Servlets, Filters and Listeners.
2018-12-18 17:49:45.560  WARN 448 --- [  restartedMain] o.o.cdi.eager.EagerBeansRepository       : Could not instantiate eager application scoped beans. Possibly the CDI application scope is not active. This is known to be the case in certain Tomcat and Jetty based configurations.

org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.ApplicationScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:123) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.omnifaces.cdi.eager.EagerBeansRepository$Proxy$_$$_WeldClientProxy.hasAnyApplicationScopedBeans(Unknown Source) ~[omnifaces-3.2.jar:3.2]
	at org.omnifaces.cdi.eager.EagerBeansRepository.instantiateApplicationScopedAndRegisterListenerIfNecessary(EagerBeansRepository.java:78) ~[omnifaces-3.2.jar:3.2]
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:83) ~[omnifaces-3.2.jar:3.2]
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createDeploymentManager(UndertowServletWebServerFactory.java:284) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:208) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.institutes.inventorymanager.InventoryManagerApplication.main(InventoryManagerApplication.java:21) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.1.1.RELEASE.jar:2.1.1.RELEASE]

2018-12-18 17:49:45.563 ERROR 448 --- [  restartedMain] org.omnifaces.ApplicationListener        : OmniFaces failed to initialize! Report an issue to OmniFaces.

java.lang.UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programatically
	at io.undertow.servlet.spec.ServletContextImpl.ensureNotProgramaticListener(ServletContextImpl.java:961) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.spec.ServletContextImpl.addListener(ServletContextImpl.java:729) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at org.omnifaces.cdi.eager.EagerBeansRepository.instantiateApplicationScopedAndRegisterListenerIfNecessary(EagerBeansRepository.java:88) ~[omnifaces-3.2.jar:3.2]
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:83) ~[omnifaces-3.2.jar:3.2]
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createDeploymentManager(UndertowServletWebServerFactory.java:284) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:208) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.institutes.inventorymanager.InventoryManagerApplication.main(InventoryManagerApplication.java:21) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.1.1.RELEASE.jar:2.1.1.RELEASE]

2018-12-18 17:49:45.563  WARN 448 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: java.lang.UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programatically
2018-12-18 17:49:45.568  INFO 448 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-18 17:49:45.573 ERROR 448 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: java.lang.UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programatically
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.institutes.inventorymanager.InventoryManagerApplication.main(InventoryManagerApplication.java:21) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.1.1.RELEASE.jar:2.1.1.RELEASE]
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programatically
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createDeploymentManager(UndertowServletWebServerFactory.java:284) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:208) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	... 13 common frames omitted
Caused by: java.lang.UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programatically
	at io.undertow.servlet.spec.ServletContextImpl.ensureNotProgramaticListener(ServletContextImpl.java:961) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.spec.ServletContextImpl.addListener(ServletContextImpl.java:729) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at org.omnifaces.cdi.eager.EagerBeansRepository.instantiateApplicationScopedAndRegisterListenerIfNecessary(EagerBeansRepository.java:88) ~[omnifaces-3.2.jar:3.2]
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:83) ~[omnifaces-3.2.jar:3.2]
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250) ~[undertow-servlet-2.0.16.Final.jar:2.0.16.Final]
	... 17 common frames omitted
```

**Comment by larsgrefer** [comment]
Seems like Omnifaces 3 or Weld can't handle the restart. We have to see if we can do something about that.

**Comment by melloware** [comment]
Agreed.   Hopefully you can figure something out!

**Comment by isawalha** [comment]
Hi,

I am having the same problem... is there any fix?

**Comment by ayamshchikov** [comment]
JRebel works great for that, but this is a commercial software.

**Comment by agarcialeon** [comment]
Do you have any update on this issue? 
I've seen the example projects contain the dependency but I haven't tested them personally.
Could you confirm spring dev-tools work with version 4.0.1 and up?

**Comment by feverdog** [comment]
Instead of disabling the restart, you could try to add your path to ` spring.devtools.restart.additional-exclude: yourpath/**`
Another thing that can save you from a lot of headaches, is to make sure that your facelets cache is disabled in your development environment by setting it to `joinfaces.jsf.facelets-refresh-period: 0`

**Comment by michaelhaessig** [comment]
I think i found an alternative solution, we can register a custom ResourceResolver instance that just looks on the actual file system instead of the classpath or the target directory.

By using the following ResourceResolver we can just simply save the file and reload the browser without having to compile it first.

```java
package ch.cloudlift.jsf.utils;

import javax.faces.view.facelets.ResourceResolver;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * User: Michael Hässig
 * Email: michael.haessig (at) gmail (dot) com
 * Date: 17.09.20
 * Time: 15:58
 */
public class DevelopmentResourceResolver extends ResourceResolver {

    private ResourceResolver parent;

    public DevelopmentResourceResolver(ResourceResolver parent) {
        this.parent = parent;
    }

    @Override
    public URL resolveUrl(String path) {
        // resolve via parent
        URL url = parent.resolveUrl(path);
        // if found try to lookup in resources dir
        if(url != null){
            try {
                // map from target to resources dir
                File file = new File(url.getPath().replace("target/classes", "src/main/resources"));
                if(file.exists()){
                    // only update the url if the new file exists
                    url = file.toURI().toURL();
                }
            } catch (MalformedURLException e) {
                throw new IllegalStateException(e);
            }
        }
        return url;
    }
}

```

Then we register it in applications-dev.properties to only load it when the dev profile is active:
```
joinfaces.jsf.facelets-resource-resolver=ch.cloudlift.jsf.utils.DevelopmentResourceResolver
joinfaces.jsf.facelets-refresh-period=0
```

So far this is working nicely and it improves the dev experience significantly.

**Comment by michaelhaessig** [comment]
I've just implemented this an hour ago and it might be useful to share it :)  

Not sure where exactly this would belong in the JoinFaces repo, to make it useful it would require a flag or at least a documentation entry on how to use this custom Resolver.

**Comment by melloware** [comment]
Apparently this also works well.
```
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-exclude=template/**,view/**
joinfaces.jsf.facelets-refresh-period=0
```
