### ISSUE TITLE
Joinfaces WAR Example not working in TomEE 7.x

### ISSUE THREAD

**Issue by MilgoTest** [joinfaces/joinfaces#645]
I pulled your Joinfaces Maven WAR example project, did a 'maven clean package' and started a Apache TomEE Plume 7.0.4 (tried also with 7.0.5 and 7.1.0) with the created WAR, but I'm getting an error during startup process.

```
25-Feb-2019 14:56:43.740 INFO [main] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Starting Servlet Engine: Apache Tomcat (TomEE)/8.5.20 (7.0.4)
25-Feb-2019 14:56:43.771 INFO [localhost-startStop-1] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Deploying web application archive [C:\Entwicklung\tomee\apache-tomee-plume-7.0.4\webapps\joinfaces-example-4.0.1-SNAPSHOT.war]
25-Feb-2019 14:56:43.771 INFO [localhost-startStop-1] org.apache.tomee.catalina.TomcatWebAppBuilder.init ------------------------- localhost -> /joinfaces-example-4.0.1-SNAPSHOT
25-Feb-2019 14:56:44.286 SEVERE [localhost-startStop-1] jdk.internal.reflect.NativeMethodAccessorImpl.invoke ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/joinfaces-example-4.0.1-SNAPSHOT]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module joinfaces-example-4.0.1-SNAPSHOT: null
	at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2305)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1188)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1125)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module joinfaces-example-4.0.1-SNAPSHOT: null
	at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:886)
	at org.apache.openejb.config.DeploymentLoader.load(DeploymentLoader.java:233)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2303)
	... 16 more
Caused by: java.lang.IllegalArgumentException
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.finder.AnnotationFinder.readClassDef(AnnotationFinder.java:1169)
	at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:147)
	at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:160)
	at org.apache.openejb.config.FinderFactory$OpenEJBAnnotationFinder.<init>(FinderFactory.java:546)
	at org.apache.openejb.config.FinderFactory.newFinder(FinderFactory.java:267)
	at org.apache.openejb.config.FinderFactory.create(FinderFactory.java:80)
	at org.apache.openejb.config.FinderFactory.createFinder(FinderFactory.java:69)
	at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:878)
	... 18 more

25-Feb-2019 14:56:44.286 SEVERE [localhost-startStop-1] jdk.internal.reflect.NativeMethodAccessorImpl.invoke Error deploying web application archive [...\tomee\apache-tomee-plume-7.0.4\webapps\joinfaces-example-4.0.1-SNAPSHOT.war]
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/joinfaces-example-4.0.1-SNAPSHOT]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

25-Feb-2019 14:56:44.286 INFO [localhost-startStop-1] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Deployment of web application archive [...\tomee\apache-tomee-plume-7.0.4\webapps\joinfaces-example-4.0.1-SNAPSHOT.war] has finished in [515] ms
```

Is there a known issue with TomEE 7? With current TomEE 8 milestone it seems to be working.

**Comment by larsgrefer** [comment]
Which Java version are you using?

**Comment by MilgoTest** [comment]
Tried jdk1.7.0_80 and jdk1.8.0_201.

**Comment by larsgrefer** [comment]
Joinfaces 4 requires at least Java 8. I'm not sure which java versions are supported by TomEE 7.

You could try downgrading to Joinfaces 2, which also supports Java 6 and 7.

Could you upload the war file you have built here?

**Comment by MilgoTest** [comment]
TomEE should run with Java 8: http://tomee.apache.org/tomee-1.7.0.html

THe WAR is too large for Github, so I used Zippyshare: https://www101.zippyshare.com/v/L9gR8Wfm/file.html

**Comment by larsgrefer** [comment]
TomEE fails to read `module-info` classes which are contained in some java 9+ ready libraries

**Comment by MilgoTest** [comment]
The problem doesn't change using jdk-11.0.2 to create the war and start TomEE.

**Comment by larsgrefer** [comment]
Tomee internally uses asm5 to directly read bytecode.

**Comment by MilgoTest** [comment]
Sorry, I don't get the problem. I got the maven dependency tree and there is no asmX used besides one test dependency. So why is there a conflict?

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.joinfaces:joinfaces-example >-------------------
[INFO] Building JoinFaces Example WAR 4.0.1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ joinfaces-example ---
[INFO] Verbose not supported since maven-dependency-plugin 3.0
[INFO] org.joinfaces:joinfaces-example:war:4.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.1.1.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.1.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.1:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:runtime
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.1.1.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.1.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  +- junit:junit:jar:4.12:test
[INFO] |  +- org.assertj:assertj-core:jar:3.11.1:test
[INFO] |  +- org.mockito:mockito-core:jar:2.23.4:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.5:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.1.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-test:jar:5.1.3.RELEASE:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.6.2:test
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.7:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.7:compile
[INFO] |  |  +- org.springframework:spring-context:jar:5.1.3.RELEASE:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.7:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.1.1:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
[INFO] +- org.springframework.boot:spring-boot-devtools:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.1.1.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.1.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-freemarker:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.freemarker:freemarker:jar:2.3.28:compile
[INFO] |  \- org.springframework:spring-context-support:jar:5.1.3.RELEASE:compile
[INFO] |     \- org.springframework:spring-beans:jar:5.1.3.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.1.3.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.1.2.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-core:jar:5.1.2.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.1.2.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.1.3.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.7:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.7:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.0.13.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  +- org.springframework:spring-web:jar:5.1.3.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.1.3.RELEASE:compile
[INFO] +- org.joinfaces:tomcat-spring-boot-starter:jar:4.0.1:provided
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.1.1.RELEASE:provided
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.13:provided
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.13:provided
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.13:provided
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-jasper:jar:9.0.13:provided
[INFO] |     \- org.eclipse.jdt:ecj:jar:3.13.102:provided
[INFO] +- org.joinfaces:primefaces-spring-boot-starter:jar:4.0.1:compile
[INFO] |  +- org.primefaces.extensions:resources-ckeditor:jar:6.2.10:compile
[INFO] |  +- org.joinfaces:jsf-spring-boot-starter:jar:4.0.1:compile
[INFO] |  |  \- org.joinfaces:mojarra-spring-boot-starter:jar:4.0.1:compile
[INFO] |  |     \- org.glassfish:javax.faces:jar:2.3.8:compile
[INFO] |  +- org.primefaces:primefaces:jar:6.2:compile
[INFO] |  \- org.primefaces.extensions:primefaces-extensions:jar:6.2.10:compile
[INFO] +- org.joinfaces:omnifaces1-spring-boot-starter:jar:4.0.1:compile
[INFO] |  \- org.omnifaces:omnifaces:jar:1.14.1:compile
[INFO] +- org.joinfaces:security-spring-boot-starter:jar:4.0.1:compile
[INFO] |  +- org.springframework.security:spring-security-taglibs:jar:5.1.2.RELEASE:compile
[INFO] |  \- org.joinfaces:joinfaces-security-taglib:jar:4.0.1:compile
[INFO] +- org.joinfaces:rewrite-spring-boot-starter:jar:4.0.1:compile
[INFO] |  +- org.joinfaces:joinfaces-autoconfigure:jar:4.0.1:compile
[INFO] |  |  \- io.github.classgraph:classgraph:jar:4.6.6:runtime
[INFO] |  +- org.ocpsoft.rewrite:rewrite-servlet:jar:3.4.2.Final:compile
[INFO] |  +- org.ocpsoft.rewrite:rewrite-integration-spring:jar:3.4.2.Final:compile
[INFO] |  +- org.ocpsoft.rewrite:rewrite-integration-faces:jar:3.4.2.Final:compile
[INFO] |  \- org.ocpsoft.logging:logging-adapter-slf4j:jar:1.0.5.Final:compile
[INFO] +- commons-fileupload:commons-fileupload:jar:1.3.3:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.4:compile
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.141.5:test
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:3.141.5:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.9.5:test
[INFO] |  +- org.apache.commons:commons-exec:jar:1.3:test
[INFO] |  +- com.google.guava:guava:jar:25.0-jre:test
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:1.3.9:test
[INFO] |  |  +- org.checkerframework:checker-compat-qual:jar:2.0.0:test
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:test
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:test
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:test
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.11.0:test
[INFO] |  \- com.squareup.okio:okio:jar:1.14.0:test
[INFO] +- org.seleniumhq.selenium:htmlunit-driver:jar:2.33.2:test
[INFO] +- net.sourceforge.htmlunit:htmlunit:jar:2.33:test
[INFO] |  +- xalan:xalan:jar:2.7.2:test
[INFO] |  |  \- xalan:serializer:jar:2.7.2:test
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.4:test
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.6:test
[INFO] |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.33:test
[INFO] |  +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.33:test
[INFO] |  |  \- xerces:xercesImpl:jar:2.12.0:test
[INFO] |  |     \- xml-apis:xml-apis:jar:1.4.01:test
[INFO] |  +- net.sourceforge.htmlunit:htmlunit-cssparser:jar:1.2.0:test
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- commons-net:commons-net:jar:3.6:test
[INFO] |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.4.12.v20180830:test
[INFO] |     +- org.eclipse.jetty:jetty-client:jar:9.4.12.v20180830:test
[INFO] |     |  \- org.eclipse.jetty:jetty-http:jar:9.4.12.v20180830:test
[INFO] |     +- org.eclipse.jetty:jetty-xml:jar:9.4.12.v20180830:test
[INFO] |     +- org.eclipse.jetty:jetty-util:jar:9.4.12.v20180830:test
[INFO] |     +- org.eclipse.jetty:jetty-io:jar:9.4.12.v20180830:test
[INFO] |     \- org.eclipse.jetty.websocket:websocket-common:jar:9.4.12.v20180830:test
[INFO] |        \- org.eclipse.jetty.websocket:websocket-api:jar:9.4.12.v20180830:test
[INFO] +- io.github.bonigarcia:webdrivermanager:jar:3.0.0:test
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.6:test
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.10:test
[INFO] |  |  \- commons-codec:commons-codec:jar:1.11:test
[INFO] |  \- org.jsoup:jsoup:jar:1.11.3:test
[INFO] +- org.rauschig:jarchivelib:jar:1.0.0:test
[INFO] |  \- org.apache.commons:commons-compress:jar:1.18:test
[INFO] +- javax.enterprise:cdi-api:jar:2.0.SP1:compile
[INFO] |  +- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO] |  \- javax.inject:javax.inject:jar:1:compile
[INFO] +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
[INFO] |  +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
[INFO] |  +- org.jvnet.staxex:stax-ex:jar:1.8:compile
[INFO] |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
[INFO] |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] \- org.apache.maven:maven-model:jar:3.6.0:compile
[INFO]    \- org.codehaus.plexus:plexus-utils:jar:3.1.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.597 s
[INFO] Finished at: 2019-02-28T16:40:54+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by larsgrefer** [comment]
ASM 5 is inside TomEE 7.0.x itself (`apache-tomee-plume-7.0.2/lib/xbean-asm5-shaded-4.5.jar`).
The OpenEJB Container inside TomEE 7.0.x uses ASM 5 to scan the deployed applications for annotations and fails when it encounters a Java 9 `module-info` class.

TomEE 7.1.0, however, contains ASM 6 and could work better.

Also you should make sure to mark everthing as `provided` in your pom, which is already present in TomEE Plume:
- several JavaEE apis (CDI, JSF, JAXB, ...)
- Mojarra, JAXB Impl, Jasper
