### ISSUE TITLE
Use joinfaces with war packaging

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#77]
joinfaces is designed with **jar** packaging in mind, but working with **war** packaging could be a plus.

I've done some investigation with joinfaces starters version **2.2.5** and with jsf resources located at **src/main/webapp** with [joinfaces-example-war](https://github.com/joinfaces/joinfaces-example-war)

According to [Spring Boot Reference](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html#howto-create-a-deployable-war-file), some changes should be done:
- Main Application/Configuration class should extends SpringBootServletInitializer and override its configure method
- change pom packaging to war
- mark the embedded servlet container dependency as provided

| jsf starter | result inside servlet container | result with executable war (java -jar .war) |
| --- | --- | --- |
| jsf-spring-boot-starter | **Ok tomcat 8.5.5 and 7.0.72** | **Ok** |
| jsf-jetty-spring-boot-starter | **Ok jetty 9.3.12** spring-boot-devtools and org.mortbay.jasper:apache-jsp removed | **Ok** exclude JettySpringBootAutoConfiguration |
| jsf-undertow-spring-boot-starter | **Fail wildfly 10.1.0.Final** No visible WebSecurityExpressionHandler | **Ok** exclude UndertowSpringBootAutoConfiguration |
| jsf-myfaces-spring-boot-starter | **Ok tomcat 8.5.5 and 7.0.72** | **Ok** |
| jsf-myfaces-jetty-spring-boot-starter | **Fail jetty 9.3.12** No visible WebSecurityExpressionHandler; spring-boot-devtools and org.mortbay.jasper:apache-jsp removed | **Ok** exclude JettySpringBootAutoConfiguration |
| jsf-myfaces-undertow-spring-boot-starter | **Fail wildfly 10.1.0.Final** NoSuchMethodError: DigesterFactory.newDigester(RuleSet;Digester) | **Ok** exclude UndertowSpringBootAutoConfiguration |

**Comment by ayamshchikov** [comment]
Hi @persapiens,
Is web.xml processed during deployment?
There are some configurations there, like  mapping page on exception (ex. ViewExpired), session timeout, welcome file list.
Seems like it is not used, or that stuff should be configured in the aplication.properties file?

**Comment by persapiens** [comment]
Hello @ayamshchikov ,

web.xml is not processed when servlet container is embedded.
Use `application.properties` or `application.yml`. It is the way to configure spring boot application. 
See [common application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html).
Example about configuring JSF [here.](https://github.com/joinfaces/joinfaces/blob/master/jsf-spring-boot-autoconfigure/src/test/resources/application.yml)
The other possibility is to create [configuration classes.](http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-configuration-classes.html)

**Comment by ayamshchikov** [comment]
Thanks, @persapiens - I'll play with those properties.
However, seems like there is no property for web.xml elements, like:
<filter>, <error-page>,  <listener>, <welcome-file-list>
Do I have to configure those somehow differently?

**Comment by persapiens** [comment]
`<filter> and <listener>` should be added programmatically like [here.](http://stackoverflow.com/questions/28566261/spring-boot-convert-web-xml-listener)

Take a look to [customize error page.](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-actuator.html#howto-customize-the-whitelabel-error-page)

**Comment by ayamshchikov** [comment]
thanks, @persapiens  for sharing this information!

**Comment by larsgrefer** [comment]
I get the following exception when I run a simple packaged `war` with `java -jar`

```
2017-02-26 12:02:35.214  WARN 23681 --- [ost-startStop-1] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [war:file:/Users/larsgrefer/git/joinfaces-gradle-example/war-example/build/libs/war-example.war*/WEB-INF/classes/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[reflections-0.9.10.jar!/:na]
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[reflections-0.9.10.jar!/:na]
        at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar!/:na]
        at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar!/:na]
        at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar!/:na]
        at org.joinfaces.JsfClassFactory.computeClasses(JsfClassFactory.java:185) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
        at org.joinfaces.JsfClassFactory.getAnnotatedClassMap(JsfClassFactory.java:157) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
        at org.joinfaces.JsfClassFactory.getAnnotatedClasses(JsfClassFactory.java:215) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
        at org.joinfaces.JsfClassFactory.getAllClasses(JsfClassFactory.java:204) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
        at org.joinfaces.mojarra.MojarraServletContextInitializer.onStartup(MojarraServletContextInitializer.java:76) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:229) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

```

**Comment by larsgrefer** [comment]
With `2.3.7-SNAPSHOT` the `org.reflections.ReflectionsException` is gone.

**Comment by larsgrefer** [comment]
It seems like JSF (Mojarra) is initialized twice when running a repackaged war with `java -jar`

* JSF complaines about the managed beans `now` and `startup` declared twice.
* Primefaces, Primefaces Extensions and Omifaces log their version number twice.

Running the same application using `./gradlew war-example:bootRun` works fine.

```
larsgrefer@... ~/g/j/w/b/libs (develop)> java -jar war-example.war 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.3.RELEASE)

2017-05-06 23:57:41.498  INFO 19074 --- [           main] o.j.example.WarExampleApplication        : Starting WarExampleApplication on ... with PID 19074 (/Users/larsgrefer/git/joinfaces-gradle-example/war-example/build/libs/war-example.war started by larsgrefer in /Users/larsgrefer/git/joinfaces-gradle-example/war-example/build/libs)
2017-05-06 23:57:41.504  INFO 19074 --- [           main] o.j.example.WarExampleApplication        : No active profile set, falling back to default profiles: default
2017-05-06 23:57:41.666  INFO 19074 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2328c243: startup date [Sat May 06 23:57:41 CEST 2017]; root of context hierarchy
2017-05-06 23:57:43.451  INFO 19074 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-05-06 23:57:43.773  INFO 19074 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.joinfaces.javaxfaces.ProjectStageAutoConfiguration' of type [org.joinfaces.javaxfaces.ProjectStageAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-05-06 23:57:44.401  INFO 19074 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-05-06 23:57:44.432  INFO 19074 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-05-06 23:57:44.435  INFO 19074 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.14
2017-05-06 23:57:47.847  INFO 19074 --- [ost-startStop-1] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2017-05-06 23:57:48.579  INFO 19074 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-05-06 23:57:48.580  INFO 19074 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6918 ms
2017-05-06 23:57:50.212  INFO 19074 --- [ost-startStop-1] org.reflections.Reflections              : Reflections took 998 ms to scan 5 urls, producing 691 keys and 3621 values 
2017-05-06 23:57:51.147  INFO 19074 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-05-06 23:57:51.155  INFO 19074 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-05-06 23:57:51.156  INFO 19074 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-05-06 23:57:51.156  INFO 19074 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-05-06 23:57:51.156  INFO 19074 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-05-06 23:57:51.284  INFO 19074 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.config     : Mojarra 2.2.14 ( 20161114-2152 unable to get svn info) für Kontext '' wird initialisiert.
2017-05-06 23:57:53.243  INFO 19074 --- [ost-startStop-1] j.e.r.webcontainer.jsf.application       : JSF1048: PostConstruct/PreDestroy-Annotationen vorhanden.  Verwaltete Bean-Methoden, die mit diesen Annotationen markiert sind, lassen die entsprechenden Annotationen verarbeiten.
2017-05-06 23:57:53.669  WARN 19074 --- [ost-startStop-1] j.e.r.webcontainer.jsf.managedbean       : JSF1074: Verwalteter Bean mit dem Namen 'startup' wurde bereits registriert.  Ersetzen des bestehenden Klassentyps des verwalteten Beans java.util.Date durch java.util.Date.
2017-05-06 23:57:53.670  WARN 19074 --- [ost-startStop-1] j.e.r.webcontainer.jsf.managedbean       : JSF1074: Verwalteter Bean mit dem Namen 'now' wurde bereits registriert.  Ersetzen des bestehenden Klassentyps des verwalteten Beans java.util.Date durch java.util.Date.
2017-05-06 23:57:55.800  INFO 19074 --- [ost-startStop-1] .w.PostConstructApplicationEventListener : Running on PrimeFaces 6.1
2017-05-06 23:57:55.801  INFO 19074 --- [ost-startStop-1] .w.PostConstructApplicationEventListener : Running on PrimeFaces 6.1
2017-05-06 23:57:55.801  INFO 19074 --- [ost-startStop-1] .a.PostConstructApplicationEventListener : Running on PrimeFaces Extensions 6.1
2017-05-06 23:57:55.801  INFO 19074 --- [ost-startStop-1] .a.PostConstructApplicationEventListener : Running on PrimeFaces Extensions 6.1
2017-05-06 23:57:55.801  INFO 19074 --- [ost-startStop-1] o.omnifaces.VersionLoggerEventListener   : Using OmniFaces version 1.14
2017-05-06 23:57:55.801  INFO 19074 --- [ost-startStop-1] o.omnifaces.VersionLoggerEventListener   : Using OmniFaces version 1.14
2017-05-06 23:57:56.190  INFO 19074 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2328c243: startup date [Sat May 06 23:57:41 CEST 2017]; root of context hierarchy
2017-05-06 23:57:56.315  INFO 19074 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-05-06 23:57:56.317  INFO 19074 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-05-06 23:57:56.365  INFO 19074 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-05-06 23:57:56.365  INFO 19074 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-05-06 23:57:56.433  INFO 19074 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-05-06 23:57:57.213  INFO 19074 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-05-06 23:57:57.399  INFO 19074 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-05-06 23:57:57.408  INFO 19074 --- [           main] o.j.example.WarExampleApplication        : Started WarExampleApplication in 16.538 seconds (JVM running for 17.323)
```

**Comment by larsgrefer** [comment]
Running a repacked war in a standalone tomcat seems to start two application contexts, is this intended?

**Comment by persapiens** [comment]
No. The error you reported above occurs at the second initialization.

**Comment by ojuniorbezerra** [comment]
I'm using joinfaces and trying to get up with wildfly 10, but it's like having a tomcat embedded inside the dependency.
It starts but when it almost ends it gives error: NoSuchMethodError: DigesterFactory.newDigester
dependency jsf-spring-boot-starter

**Comment by persapiens** [comment]
hi @ojuniorbezerra , try undertow specific starters.

**Comment by ojuniorbezerra** [comment]
Hi, @persapiens you say jsf-myfaces-undertow-spring-boot-starter like dependency instead jsf-spring-boot-starter? but a use JSF, CDI and primefaces.

**Comment by larsgrefer** [comment]
@persapiens Is this issue still relevant?

https://github.com/joinfaces/joinfaces-gradle-war-example is a working example for a war-file which can be both
- deployed to an existing servlet container and
- used as standalone application

**Comment by persapiens** [comment]
I agree with you. Closing issue.
