### ISSUE TITLE
Migration-Problem JF 2 -> 3: java.lang.IllegalStateException: Kein Rügriff für javax.faces.context.FacesContextFactory gefunden.

### ISSUE THREAD

**Issue by pkrummen** [joinfaces/joinfaces#798]
Hello, 
Migrating from JF 2 to 3, I have the problem below. 
Thank you for any help, Philipp

SCHWERWIEGEND: Die Anwendung wurde bei Systemstart nicht einwandfrei initialisiert, Factory konnte nicht gefunden werden: javax.faces.context.FacesContextFactory. Rügriff versucht.
Mär 25, 2020 4:01:11 PM org.apache.catalina.core.ApplicationContext log
SCHWERWIEGEND: StandardWrapper.Throwable
java.lang.IllegalStateException: Kein Rügriff für javax.faces.context.FacesContextFactory gefunden.
                at javax.faces.FactoryFinder$FactoryManager.getFactory(FactoryFinder.java:1008)
                at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:343)
                at javax.faces.webapp.FacesServlet.init(FacesServlet.java:302)
                at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
                at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)

[application.txt](https://github.com/joinfaces/joinfaces/files/4383202/application.txt)
[pom_eff.txt](https://github.com/joinfaces/joinfaces/files/4383203/pom_eff.txt)
[Konsole.txt](https://github.com/joinfaces/joinfaces/files/4383204/Konsole.txt)

**Comment by larsgrefer** [comment]
Can you provide an example project which I can examine?

**Comment by pkrummen** [comment]
Hello, 

I got rid of the problem with some changes: 
- use embedded undertow instead of tomcat
- turned off:  support-jsp-and-faces-el: false
(see below)

So, for me its solved, many thanks, 
Philipp
... 
joinfaces:
  myfaces:
    # disable jsp/jasper dependencies
    support-jsp-and-faces-el: false
