### ISSUE TITLE
joinfaces.myfaces.automatic-extensionless-mapping=true

### ISSUE THREAD

**Issue by vitsin** [joinfaces/joinfaces#841]
Joinfaces: 4.3.4
spring-boot-starter-parent: 2.3.5.RELEASE
Running on Undertow with MyFaces

When set **joinfaces.myfaces.automatic-extensionless-mapping=true** every directory in the src/main/resources/ returns the following error message:
```
05-Nov.-2020 18:37:20,944 [restartedMain] ERROR javax.faces.view.ViewDeclarationLanguage %PARSER_ERROR[x] [j.f.v.ViewDeclarationLanguage:107] - Malformed URL viewId: C:\bla\target\classes\META-INF\resources\template
java.net.MalformedURLException: UT010021: Path C:\bla\target\classes\META-INF\resources\template must start with a /
	at io.undertow.servlet.spec.ServletContextImpl.getResource(ServletContextImpl.java:293)
	at org.apache.myfaces.context.servlet.ServletExternalContextImplBase.getResource(ServletExternalContextImplBase.java:131)
	at javax.faces.view.ViewDeclarationLanguage.viewExists(ViewDeclarationLanguage.java:100)
	at org.apache.myfaces.view.jsp.JspViewDeclarationLanguage.viewExists(JspViewDeclarationLanguage.java:257)
	at org.apache.myfaces.application.ResourceHandlerImpl$FilterInvalidSuffixViewResourceIterator.match(ResourceHandlerImpl.java:1859)
	at org.apache.myfaces.application.ResourceHandlerImpl$FilterInvalidSuffixViewResourceIterator.match(ResourceHandlerImpl.java:1840)
	at org.apache.myfaces.util.SkipMatchIterator.hasNext(SkipMatchIterator.java:51)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initAutomaticExtensionlessMapping(AbstractFacesInitializer.java:824)
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:246)
	at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:103)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createManager(UndertowServletWebServerFactory.java:296)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:267)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
```

```
05-Nov.-2020 18:37:20,947 [restartedMain] ERROR javax.faces.view.ViewDeclarationLanguage %PARSER_ERROR[x] [j.f.v.ViewDeclarationLanguage:107] - Malformed URL viewId: C:\bla\target\classes\META-INF\resources\css
java.net.MalformedURLException: UT010021: Path C:\bla\target\classes\META-INF\resources\css must start with a /
```

and so on for each directory.
Despite above error Undertow/MyFaces can render and show resources.

**Comment by melloware** [comment]
I would report that to JoinFaces.  I don’t use extensionless mapping so I have never seen that issue.

**Comment by larsgrefer** [comment]
Have you tried the same setup on a different operating system than windows?
I'd like to make sure, its not a undertow-windows bug.

**Comment by vitsin** [comment]
I did not try it on any system except Windows10.
Above issue is still happen on JoinFaces v4.7.5. (Oct-2022)
My system is Running with Spring Boot v2.7.4, Spring v5.3.23

**Comment by vitsin** [comment]
@larsgrefer hi, any news on this issue ? thanks
