### ISSUE TITLE
Allow override default autoconfigured rewrite SpringBootAnnotationConfigProvider

### ISSUE THREAD

**Issue by didiez** [joinfaces/joinfaces#845]
As of `joinfaces-4.3.4` there is no easy way to override the way OCPSoft rewrites annotations are scanned.
I know there is already a great way to achieve this classpath scanning at build time with joinfaces-maven-plugin, but in our usecase we cannot guarantee every final application includes this plugin in the build section (maven pom.xml).
We have a custom starter which includes joinfaces and rewrite (among others). This starter is declared as dependency in other simple spring-boot (spring-boot-starter-parent) apps providing all the configuration for jsf integration, service discovery, etc.

It would be great if the default `HttpConfigurationProvider` (`SpringBootAnnotationConfigProvider`) were only registered as a bean if not provided manually. This could be achieve by simply annotating the method with `ConditionalOnMissingBean`:
```java
@Bean
@ConditionalOnMissingBean(HttpConfigurationProvider.class)
public SpringBootAnnotationConfigProvider rewriteAnnotationConfigProvider(RewriteProperties rewriteProperties) {
	return new SpringBootAnnotationConfigProvider(rewriteProperties.getAnnotationConfigProvider());
}
```

In the meantime, I have workarounded this with a `BeanFactoryPostProcessor` but feels a bit hacky.

**Comment by larsgrefer** [comment]
Have you tried to set `joinfaces.rewrite.annotation-config-provider.enabled=false` in order to disable the ConfigProvider?

**Comment by larsgrefer** [comment]
Why do you need a custom rewriteAnnotationConfigProvider? Could we improve our implementation somehow?

**Comment by didiez** [comment]
I have written a simplified showcase to reproduce the problems we have using the default `rewriteAnnotationConfigProvider`.
https://github.com/didiez/joinfaces-rewrite-starter-issue-showcase

We have a custom starter (`custom-starter` in the showcase) which includes joinfaces among other autoconfiguration stuff (spring-cloud, etc).
Other applications depends on the `custom-starter`, and transitively on joinfaces, rewrite, ...

Our `rewriteAnnotationConfigProvider` find all rewrite rules defined in libraries with a `faces-config.xml` resources (used as a marker), while the default implementation stops when a resource `META-INF/joinfaces/org.ocpsoft.rewrite.annotation.spi.AnnotationHandler.classes` is found in the classpath, even when it contains only the rules inside one library (at build time)

Hope it helps.

**Comment by larsgrefer** [comment]
The classpath scan goal should not be used in library projects (like `custom-starter`), but only in the final application project (like `app`).

**Comment by didiez** [comment]
Yes, it seems reasonable, but we cannot guarantee that every app that depends on `custom-starter` contains the `joinfaces-faces-plugin` in their build plugins section.
Without the `classpath-scan` goal (not in the library nor in the final application) the app crash with a OOME at startup:
```
Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar!/:4.8.78]
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1319) ~[classgraph-4.8.78.jar!/:4.8.78]
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1337) ~[classgraph-4.8.78.jar!/:4.8.78]
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1350) ~[classgraph-4.8.78.jar!/:4.8.78]
        at org.joinfaces.autoconfigure.servlet.initializer.ServletContainerInitializerRegistrationBean.performClasspathScan(ServletContainerInitializerRegistrationBean.java:123) ~[joinfaces-autoconfigure-4.3.4.jar!/:4.3.4]
        at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
        at org.joinfaces.autoconfigure.servlet.initializer.ServletContainerInitializerRegistrationBean.getClasses(ServletContainerInitializerRegistrationBean.java:71) ~[joinfaces-autoconfigure-4.3.4.jar!/:4.3.4]
        at org.joinfaces.autoconfigure.servlet.initializer.ServletContainerInitializerRegistrationBean.lambda$customize$0(ServletContainerInitializerRegistrationBean.java:66) ~[joinfaces-autoconfigure-4.3.4.jar!/:4.3.4]
        at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
        ... 22 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
```
That's why we added the `classpath-scan` goal on the library. Increasing the heap it is not an option as it was working ok with the previous configuration.

Any thoughts on this? Is there a way in maven to execute a plugin goal "inherited" from a dependency?

**Comment by larsgrefer** [comment]
What heap size do you use? This OOME should not happen.

In order to find everything, the classpath scan needs to scan the whole classpath at once. The only places where the complete classpath is known, is
1. at runtime (obviously) or
2. when the application is built and the whole classpath is known to maven/gradle

The most correct place to do the classpath scan is therefore at runtime, when the app starts.
Since this can slow down the startup significantly, we provide the maven and gradle plugins, to make it possible to perform the classpath scan at build-time. For this to work correctly, the complete classpath must be known at build time. This can only work for the application build and only if all (provided or optional) dependencies are declared correctly.

> Is there a way in maven to execute a plugin goal "inherited" from a dependency?

No.
The only way (in maven) to inherit a plugin execution, is from a parent project.

**Comment by didiez** [comment]
> What heap size do you use? This OOME should not happen.

It depends mostly on the requirements. In small apps we could go as low as `-Xmx150m`
I have added a simple script `test.sh` to reproduce the OOME in https://github.com/didiez/joinfaces-rewrite-starter-issue-showcase
> In order to find everything, the classpath scan needs to scan the whole classpath at once. The only places where the complete classpath is known, is
> 
> 1. at runtime (obviously) or
> 2. when the application is built and the whole classpath is known to maven/gradle
> 
> The most correct place to do the classpath scan is therefore at runtime, when the app starts.

I also prefer runtime scanning when the impact in startup times is acceptable (hundreds ms/few secs).

**Comment by didiez** [comment]
> Without the `classpath-scan` goal (not in the library nor in the final application) the app crash with a OOME at startup:
> 
> ```
> Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
>         ...
>         at org.joinfaces.autoconfigure.servlet.initializer.ServletContainerInitializerRegistrationBean.performClasspathScan(ServletContainerInitializerRegistrationBean.java:123) ~[joinfaces-autoconfigure-4.3.4.jar!/:4.3.4]
>         ...
I was looking at the wrong place, the OOME was thrown by `ServletContainerInitializerRegistrationBean` not `SpringBootAnnotationConfigProvider`. However, it is also related to classgraph scanning at runtime.

We have increased the heap to prevent OOME on startup. It is not a big deal, a bit annoying though. 
If this issue arises again in the future, we could change the classpath scanning to make it less aggresive, filtering out certain resources/jars

Thanks for your help @larsgrefer!
